// Code generated by ent, DO NOT EDIT.

package chain

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the chain type in the database.
	Label = "chain"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChainID holds the string denoting the chain_id field in the database.
	FieldChainID = "chain_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldNativeSymbol holds the string denoting the native_symbol field in the database.
	FieldNativeSymbol = "native_symbol"
	// FieldConfirmations holds the string denoting the confirmations field in the database.
	FieldConfirmations = "confirmations"
	// FieldScanBatchSize holds the string denoting the scan_batch_size field in the database.
	FieldScanBatchSize = "scan_batch_size"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the chain in the database.
	Table = "chains"
)

// Columns holds all SQL columns for chain fields.
var Columns = []string{
	FieldID,
	FieldChainID,
	FieldName,
	FieldNativeSymbol,
	FieldConfirmations,
	FieldScanBatchSize,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ChainIDValidator is a validator for the "chain_id" field. It is called by the builders before save.
	ChainIDValidator func(int) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// NativeSymbolValidator is a validator for the "native_symbol" field. It is called by the builders before save.
	NativeSymbolValidator func(string) error
	// DefaultConfirmations holds the default value on creation for the "confirmations" field.
	DefaultConfirmations int
	// DefaultScanBatchSize holds the default value on creation for the "scan_batch_size" field.
	DefaultScanBatchSize int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int8
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Chain queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByChainID orders the results by the chain_id field.
func ByChainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChainID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByNativeSymbol orders the results by the native_symbol field.
func ByNativeSymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNativeSymbol, opts...).ToFunc()
}

// ByConfirmations orders the results by the confirmations field.
func ByConfirmations(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmations, opts...).ToFunc()
}

// ByScanBatchSize orders the results by the scan_batch_size field.
func ByScanBatchSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScanBatchSize, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
