// Code generated by ent, DO NOT EDIT.

package chain

import (
	"nexus-chain/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Chain {
	return predicate.Chain(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Chain {
	return predicate.Chain(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Chain {
	return predicate.Chain(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Chain {
	return predicate.Chain(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Chain {
	return predicate.Chain(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Chain {
	return predicate.Chain(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Chain {
	return predicate.Chain(sql.FieldLTE(FieldID, id))
}

// ChainID applies equality check predicate on the "chain_id" field. It's identical to ChainIDEQ.
func ChainID(v int) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldChainID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldName, v))
}

// NativeSymbol applies equality check predicate on the "native_symbol" field. It's identical to NativeSymbolEQ.
func NativeSymbol(v string) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldNativeSymbol, v))
}

// Confirmations applies equality check predicate on the "confirmations" field. It's identical to ConfirmationsEQ.
func Confirmations(v int) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldConfirmations, v))
}

// ScanBatchSize applies equality check predicate on the "scan_batch_size" field. It's identical to ScanBatchSizeEQ.
func ScanBatchSize(v int) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldScanBatchSize, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int8) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldUpdatedAt, v))
}

// ChainIDEQ applies the EQ predicate on the "chain_id" field.
func ChainIDEQ(v int) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldChainID, v))
}

// ChainIDNEQ applies the NEQ predicate on the "chain_id" field.
func ChainIDNEQ(v int) predicate.Chain {
	return predicate.Chain(sql.FieldNEQ(FieldChainID, v))
}

// ChainIDIn applies the In predicate on the "chain_id" field.
func ChainIDIn(vs ...int) predicate.Chain {
	return predicate.Chain(sql.FieldIn(FieldChainID, vs...))
}

// ChainIDNotIn applies the NotIn predicate on the "chain_id" field.
func ChainIDNotIn(vs ...int) predicate.Chain {
	return predicate.Chain(sql.FieldNotIn(FieldChainID, vs...))
}

// ChainIDGT applies the GT predicate on the "chain_id" field.
func ChainIDGT(v int) predicate.Chain {
	return predicate.Chain(sql.FieldGT(FieldChainID, v))
}

// ChainIDGTE applies the GTE predicate on the "chain_id" field.
func ChainIDGTE(v int) predicate.Chain {
	return predicate.Chain(sql.FieldGTE(FieldChainID, v))
}

// ChainIDLT applies the LT predicate on the "chain_id" field.
func ChainIDLT(v int) predicate.Chain {
	return predicate.Chain(sql.FieldLT(FieldChainID, v))
}

// ChainIDLTE applies the LTE predicate on the "chain_id" field.
func ChainIDLTE(v int) predicate.Chain {
	return predicate.Chain(sql.FieldLTE(FieldChainID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Chain {
	return predicate.Chain(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Chain {
	return predicate.Chain(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Chain {
	return predicate.Chain(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Chain {
	return predicate.Chain(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Chain {
	return predicate.Chain(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Chain {
	return predicate.Chain(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Chain {
	return predicate.Chain(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Chain {
	return predicate.Chain(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Chain {
	return predicate.Chain(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Chain {
	return predicate.Chain(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Chain {
	return predicate.Chain(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Chain {
	return predicate.Chain(sql.FieldContainsFold(FieldName, v))
}

// NativeSymbolEQ applies the EQ predicate on the "native_symbol" field.
func NativeSymbolEQ(v string) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldNativeSymbol, v))
}

// NativeSymbolNEQ applies the NEQ predicate on the "native_symbol" field.
func NativeSymbolNEQ(v string) predicate.Chain {
	return predicate.Chain(sql.FieldNEQ(FieldNativeSymbol, v))
}

// NativeSymbolIn applies the In predicate on the "native_symbol" field.
func NativeSymbolIn(vs ...string) predicate.Chain {
	return predicate.Chain(sql.FieldIn(FieldNativeSymbol, vs...))
}

// NativeSymbolNotIn applies the NotIn predicate on the "native_symbol" field.
func NativeSymbolNotIn(vs ...string) predicate.Chain {
	return predicate.Chain(sql.FieldNotIn(FieldNativeSymbol, vs...))
}

// NativeSymbolGT applies the GT predicate on the "native_symbol" field.
func NativeSymbolGT(v string) predicate.Chain {
	return predicate.Chain(sql.FieldGT(FieldNativeSymbol, v))
}

// NativeSymbolGTE applies the GTE predicate on the "native_symbol" field.
func NativeSymbolGTE(v string) predicate.Chain {
	return predicate.Chain(sql.FieldGTE(FieldNativeSymbol, v))
}

// NativeSymbolLT applies the LT predicate on the "native_symbol" field.
func NativeSymbolLT(v string) predicate.Chain {
	return predicate.Chain(sql.FieldLT(FieldNativeSymbol, v))
}

// NativeSymbolLTE applies the LTE predicate on the "native_symbol" field.
func NativeSymbolLTE(v string) predicate.Chain {
	return predicate.Chain(sql.FieldLTE(FieldNativeSymbol, v))
}

// NativeSymbolContains applies the Contains predicate on the "native_symbol" field.
func NativeSymbolContains(v string) predicate.Chain {
	return predicate.Chain(sql.FieldContains(FieldNativeSymbol, v))
}

// NativeSymbolHasPrefix applies the HasPrefix predicate on the "native_symbol" field.
func NativeSymbolHasPrefix(v string) predicate.Chain {
	return predicate.Chain(sql.FieldHasPrefix(FieldNativeSymbol, v))
}

// NativeSymbolHasSuffix applies the HasSuffix predicate on the "native_symbol" field.
func NativeSymbolHasSuffix(v string) predicate.Chain {
	return predicate.Chain(sql.FieldHasSuffix(FieldNativeSymbol, v))
}

// NativeSymbolEqualFold applies the EqualFold predicate on the "native_symbol" field.
func NativeSymbolEqualFold(v string) predicate.Chain {
	return predicate.Chain(sql.FieldEqualFold(FieldNativeSymbol, v))
}

// NativeSymbolContainsFold applies the ContainsFold predicate on the "native_symbol" field.
func NativeSymbolContainsFold(v string) predicate.Chain {
	return predicate.Chain(sql.FieldContainsFold(FieldNativeSymbol, v))
}

// ConfirmationsEQ applies the EQ predicate on the "confirmations" field.
func ConfirmationsEQ(v int) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldConfirmations, v))
}

// ConfirmationsNEQ applies the NEQ predicate on the "confirmations" field.
func ConfirmationsNEQ(v int) predicate.Chain {
	return predicate.Chain(sql.FieldNEQ(FieldConfirmations, v))
}

// ConfirmationsIn applies the In predicate on the "confirmations" field.
func ConfirmationsIn(vs ...int) predicate.Chain {
	return predicate.Chain(sql.FieldIn(FieldConfirmations, vs...))
}

// ConfirmationsNotIn applies the NotIn predicate on the "confirmations" field.
func ConfirmationsNotIn(vs ...int) predicate.Chain {
	return predicate.Chain(sql.FieldNotIn(FieldConfirmations, vs...))
}

// ConfirmationsGT applies the GT predicate on the "confirmations" field.
func ConfirmationsGT(v int) predicate.Chain {
	return predicate.Chain(sql.FieldGT(FieldConfirmations, v))
}

// ConfirmationsGTE applies the GTE predicate on the "confirmations" field.
func ConfirmationsGTE(v int) predicate.Chain {
	return predicate.Chain(sql.FieldGTE(FieldConfirmations, v))
}

// ConfirmationsLT applies the LT predicate on the "confirmations" field.
func ConfirmationsLT(v int) predicate.Chain {
	return predicate.Chain(sql.FieldLT(FieldConfirmations, v))
}

// ConfirmationsLTE applies the LTE predicate on the "confirmations" field.
func ConfirmationsLTE(v int) predicate.Chain {
	return predicate.Chain(sql.FieldLTE(FieldConfirmations, v))
}

// ScanBatchSizeEQ applies the EQ predicate on the "scan_batch_size" field.
func ScanBatchSizeEQ(v int) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldScanBatchSize, v))
}

// ScanBatchSizeNEQ applies the NEQ predicate on the "scan_batch_size" field.
func ScanBatchSizeNEQ(v int) predicate.Chain {
	return predicate.Chain(sql.FieldNEQ(FieldScanBatchSize, v))
}

// ScanBatchSizeIn applies the In predicate on the "scan_batch_size" field.
func ScanBatchSizeIn(vs ...int) predicate.Chain {
	return predicate.Chain(sql.FieldIn(FieldScanBatchSize, vs...))
}

// ScanBatchSizeNotIn applies the NotIn predicate on the "scan_batch_size" field.
func ScanBatchSizeNotIn(vs ...int) predicate.Chain {
	return predicate.Chain(sql.FieldNotIn(FieldScanBatchSize, vs...))
}

// ScanBatchSizeGT applies the GT predicate on the "scan_batch_size" field.
func ScanBatchSizeGT(v int) predicate.Chain {
	return predicate.Chain(sql.FieldGT(FieldScanBatchSize, v))
}

// ScanBatchSizeGTE applies the GTE predicate on the "scan_batch_size" field.
func ScanBatchSizeGTE(v int) predicate.Chain {
	return predicate.Chain(sql.FieldGTE(FieldScanBatchSize, v))
}

// ScanBatchSizeLT applies the LT predicate on the "scan_batch_size" field.
func ScanBatchSizeLT(v int) predicate.Chain {
	return predicate.Chain(sql.FieldLT(FieldScanBatchSize, v))
}

// ScanBatchSizeLTE applies the LTE predicate on the "scan_batch_size" field.
func ScanBatchSizeLTE(v int) predicate.Chain {
	return predicate.Chain(sql.FieldLTE(FieldScanBatchSize, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int8) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int8) predicate.Chain {
	return predicate.Chain(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int8) predicate.Chain {
	return predicate.Chain(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int8) predicate.Chain {
	return predicate.Chain(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int8) predicate.Chain {
	return predicate.Chain(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int8) predicate.Chain {
	return predicate.Chain(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int8) predicate.Chain {
	return predicate.Chain(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int8) predicate.Chain {
	return predicate.Chain(sql.FieldLTE(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Chain {
	return predicate.Chain(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Chain) predicate.Chain {
	return predicate.Chain(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Chain) predicate.Chain {
	return predicate.Chain(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Chain) predicate.Chain {
	return predicate.Chain(sql.NotPredicates(p))
}
