// Code generated by ent, DO NOT EDIT.

package monitoreventcursor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the monitoreventcursor type in the database.
	Label = "monitor_event_cursor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventID holds the string denoting the event_id field in the database.
	FieldEventID = "event_id"
	// FieldScanLastBlock holds the string denoting the scan_last_block field in the database.
	FieldScanLastBlock = "scan_last_block"
	// FieldLastScannedAt holds the string denoting the last_scanned_at field in the database.
	FieldLastScannedAt = "last_scanned_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the monitoreventcursor in the database.
	Table = "monitor_event_cursors"
)

// Columns holds all SQL columns for monitoreventcursor fields.
var Columns = []string{
	FieldID,
	FieldEventID,
	FieldScanLastBlock,
	FieldLastScannedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultScanLastBlock holds the default value on creation for the "scan_last_block" field.
	DefaultScanLastBlock int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the MonitorEventCursor queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventID orders the results by the event_id field.
func ByEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventID, opts...).ToFunc()
}

// ByScanLastBlock orders the results by the scan_last_block field.
func ByScanLastBlock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScanLastBlock, opts...).ToFunc()
}

// ByLastScannedAt orders the results by the last_scanned_at field.
func ByLastScannedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastScannedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
