// Code generated by ent, DO NOT EDIT.

package monitoreventcursor

import (
	"nexus-chain/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldLTE(FieldID, id))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldEQ(FieldEventID, v))
}

// ScanLastBlock applies equality check predicate on the "scan_last_block" field. It's identical to ScanLastBlockEQ.
func ScanLastBlock(v int64) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldEQ(FieldScanLastBlock, v))
}

// LastScannedAt applies equality check predicate on the "last_scanned_at" field. It's identical to LastScannedAtEQ.
func LastScannedAt(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldEQ(FieldLastScannedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldEQ(FieldUpdatedAt, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldNotIn(FieldEventID, vs...))
}

// EventIDGT applies the GT predicate on the "event_id" field.
func EventIDGT(v uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldGT(FieldEventID, v))
}

// EventIDGTE applies the GTE predicate on the "event_id" field.
func EventIDGTE(v uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldGTE(FieldEventID, v))
}

// EventIDLT applies the LT predicate on the "event_id" field.
func EventIDLT(v uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldLT(FieldEventID, v))
}

// EventIDLTE applies the LTE predicate on the "event_id" field.
func EventIDLTE(v uuid.UUID) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldLTE(FieldEventID, v))
}

// ScanLastBlockEQ applies the EQ predicate on the "scan_last_block" field.
func ScanLastBlockEQ(v int64) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldEQ(FieldScanLastBlock, v))
}

// ScanLastBlockNEQ applies the NEQ predicate on the "scan_last_block" field.
func ScanLastBlockNEQ(v int64) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldNEQ(FieldScanLastBlock, v))
}

// ScanLastBlockIn applies the In predicate on the "scan_last_block" field.
func ScanLastBlockIn(vs ...int64) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldIn(FieldScanLastBlock, vs...))
}

// ScanLastBlockNotIn applies the NotIn predicate on the "scan_last_block" field.
func ScanLastBlockNotIn(vs ...int64) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldNotIn(FieldScanLastBlock, vs...))
}

// ScanLastBlockGT applies the GT predicate on the "scan_last_block" field.
func ScanLastBlockGT(v int64) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldGT(FieldScanLastBlock, v))
}

// ScanLastBlockGTE applies the GTE predicate on the "scan_last_block" field.
func ScanLastBlockGTE(v int64) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldGTE(FieldScanLastBlock, v))
}

// ScanLastBlockLT applies the LT predicate on the "scan_last_block" field.
func ScanLastBlockLT(v int64) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldLT(FieldScanLastBlock, v))
}

// ScanLastBlockLTE applies the LTE predicate on the "scan_last_block" field.
func ScanLastBlockLTE(v int64) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldLTE(FieldScanLastBlock, v))
}

// LastScannedAtEQ applies the EQ predicate on the "last_scanned_at" field.
func LastScannedAtEQ(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldEQ(FieldLastScannedAt, v))
}

// LastScannedAtNEQ applies the NEQ predicate on the "last_scanned_at" field.
func LastScannedAtNEQ(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldNEQ(FieldLastScannedAt, v))
}

// LastScannedAtIn applies the In predicate on the "last_scanned_at" field.
func LastScannedAtIn(vs ...time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldIn(FieldLastScannedAt, vs...))
}

// LastScannedAtNotIn applies the NotIn predicate on the "last_scanned_at" field.
func LastScannedAtNotIn(vs ...time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldNotIn(FieldLastScannedAt, vs...))
}

// LastScannedAtGT applies the GT predicate on the "last_scanned_at" field.
func LastScannedAtGT(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldGT(FieldLastScannedAt, v))
}

// LastScannedAtGTE applies the GTE predicate on the "last_scanned_at" field.
func LastScannedAtGTE(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldGTE(FieldLastScannedAt, v))
}

// LastScannedAtLT applies the LT predicate on the "last_scanned_at" field.
func LastScannedAtLT(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldLT(FieldLastScannedAt, v))
}

// LastScannedAtLTE applies the LTE predicate on the "last_scanned_at" field.
func LastScannedAtLTE(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldLTE(FieldLastScannedAt, v))
}

// LastScannedAtIsNil applies the IsNil predicate on the "last_scanned_at" field.
func LastScannedAtIsNil() predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldIsNull(FieldLastScannedAt))
}

// LastScannedAtNotNil applies the NotNil predicate on the "last_scanned_at" field.
func LastScannedAtNotNil() predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldNotNull(FieldLastScannedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MonitorEventCursor) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MonitorEventCursor) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MonitorEventCursor) predicate.MonitorEventCursor {
	return predicate.MonitorEventCursor(sql.NotPredicates(p))
}
