// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"nexus-chain/ent/chainnode"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ChainNode is the model entity for the ChainNode schema.
type ChainNode struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key ID
	ID uuid.UUID `json:"id,omitempty"`
	// Foreign key to chains.id
	ChainID int `json:"chain_id,omitempty"`
	// Node type: rpc or ws
	NodeType string `json:"node_type,omitempty"`
	// Node alias
	Name string `json:"name,omitempty"`
	// Node endpoint URL
	URL string `json:"url,omitempty"`
	// Lower value means higher priority
	Priority int `json:"priority,omitempty"`
	// Whether to enable this node (0: stop, 1: run)
	Status int8 `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChainNode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chainnode.FieldChainID, chainnode.FieldPriority, chainnode.FieldStatus:
			values[i] = new(sql.NullInt64)
		case chainnode.FieldNodeType, chainnode.FieldName, chainnode.FieldURL:
			values[i] = new(sql.NullString)
		case chainnode.FieldCreatedAt, chainnode.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case chainnode.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChainNode fields.
func (_m *ChainNode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chainnode.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case chainnode.FieldChainID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chain_id", values[i])
			} else if value.Valid {
				_m.ChainID = int(value.Int64)
			}
		case chainnode.FieldNodeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_type", values[i])
			} else if value.Valid {
				_m.NodeType = value.String
			}
		case chainnode.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case chainnode.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case chainnode.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case chainnode.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int8(value.Int64)
			}
		case chainnode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case chainnode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChainNode.
// This includes values selected through modifiers, order, etc.
func (_m *ChainNode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ChainNode.
// Note that you need to call ChainNode.Unwrap() before calling this method if this ChainNode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChainNode) Update() *ChainNodeUpdateOne {
	return NewChainNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChainNode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChainNode) Unwrap() *ChainNode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChainNode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChainNode) String() string {
	var builder strings.Builder
	builder.WriteString("ChainNode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("chain_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChainID))
	builder.WriteString(", ")
	builder.WriteString("node_type=")
	builder.WriteString(_m.NodeType)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChainNodes is a parsable slice of ChainNode.
type ChainNodes []*ChainNode
