// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nexus-chain/ent/chain"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ChainCreate is the builder for creating a Chain entity.
type ChainCreate struct {
	config
	mutation *ChainMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetChainID sets the "chain_id" field.
func (_c *ChainCreate) SetChainID(v int) *ChainCreate {
	_c.mutation.SetChainID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ChainCreate) SetName(v string) *ChainCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNativeSymbol sets the "native_symbol" field.
func (_c *ChainCreate) SetNativeSymbol(v string) *ChainCreate {
	_c.mutation.SetNativeSymbol(v)
	return _c
}

// SetConfirmations sets the "confirmations" field.
func (_c *ChainCreate) SetConfirmations(v int) *ChainCreate {
	_c.mutation.SetConfirmations(v)
	return _c
}

// SetNillableConfirmations sets the "confirmations" field if the given value is not nil.
func (_c *ChainCreate) SetNillableConfirmations(v *int) *ChainCreate {
	if v != nil {
		_c.SetConfirmations(*v)
	}
	return _c
}

// SetScanBatchSize sets the "scan_batch_size" field.
func (_c *ChainCreate) SetScanBatchSize(v int) *ChainCreate {
	_c.mutation.SetScanBatchSize(v)
	return _c
}

// SetNillableScanBatchSize sets the "scan_batch_size" field if the given value is not nil.
func (_c *ChainCreate) SetNillableScanBatchSize(v *int) *ChainCreate {
	if v != nil {
		_c.SetScanBatchSize(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChainCreate) SetStatus(v int8) *ChainCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ChainCreate) SetNillableStatus(v *int8) *ChainCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChainCreate) SetCreatedAt(v time.Time) *ChainCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChainCreate) SetNillableCreatedAt(v *time.Time) *ChainCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChainCreate) SetUpdatedAt(v time.Time) *ChainCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChainCreate) SetNillableUpdatedAt(v *time.Time) *ChainCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChainCreate) SetID(v uuid.UUID) *ChainCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChainCreate) SetNillableID(v *uuid.UUID) *ChainCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ChainMutation object of the builder.
func (_c *ChainCreate) Mutation() *ChainMutation {
	return _c.mutation
}

// Save creates the Chain in the database.
func (_c *ChainCreate) Save(ctx context.Context) (*Chain, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChainCreate) SaveX(ctx context.Context) *Chain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChainCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChainCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChainCreate) defaults() {
	if _, ok := _c.mutation.Confirmations(); !ok {
		v := chain.DefaultConfirmations
		_c.mutation.SetConfirmations(v)
	}
	if _, ok := _c.mutation.ScanBatchSize(); !ok {
		v := chain.DefaultScanBatchSize
		_c.mutation.SetScanBatchSize(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := chain.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chain.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chain.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := chain.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChainCreate) check() error {
	if _, ok := _c.mutation.ChainID(); !ok {
		return &ValidationError{Name: "chain_id", err: errors.New(`ent: missing required field "Chain.chain_id"`)}
	}
	if v, ok := _c.mutation.ChainID(); ok {
		if err := chain.ChainIDValidator(v); err != nil {
			return &ValidationError{Name: "chain_id", err: fmt.Errorf(`ent: validator failed for field "Chain.chain_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Chain.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := chain.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Chain.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NativeSymbol(); !ok {
		return &ValidationError{Name: "native_symbol", err: errors.New(`ent: missing required field "Chain.native_symbol"`)}
	}
	if v, ok := _c.mutation.NativeSymbol(); ok {
		if err := chain.NativeSymbolValidator(v); err != nil {
			return &ValidationError{Name: "native_symbol", err: fmt.Errorf(`ent: validator failed for field "Chain.native_symbol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Confirmations(); !ok {
		return &ValidationError{Name: "confirmations", err: errors.New(`ent: missing required field "Chain.confirmations"`)}
	}
	if _, ok := _c.mutation.ScanBatchSize(); !ok {
		return &ValidationError{Name: "scan_batch_size", err: errors.New(`ent: missing required field "Chain.scan_batch_size"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Chain.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Chain.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Chain.updated_at"`)}
	}
	return nil
}

func (_c *ChainCreate) sqlSave(ctx context.Context) (*Chain, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChainCreate) createSpec() (*Chain, *sqlgraph.CreateSpec) {
	var (
		_node = &Chain{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chain.Table, sqlgraph.NewFieldSpec(chain.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ChainID(); ok {
		_spec.SetField(chain.FieldChainID, field.TypeInt, value)
		_node.ChainID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(chain.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.NativeSymbol(); ok {
		_spec.SetField(chain.FieldNativeSymbol, field.TypeString, value)
		_node.NativeSymbol = value
	}
	if value, ok := _c.mutation.Confirmations(); ok {
		_spec.SetField(chain.FieldConfirmations, field.TypeInt, value)
		_node.Confirmations = value
	}
	if value, ok := _c.mutation.ScanBatchSize(); ok {
		_spec.SetField(chain.FieldScanBatchSize, field.TypeInt, value)
		_node.ScanBatchSize = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(chain.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chain.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chain.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Chain.Create().
//		SetChainID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChainUpsert) {
//			SetChainID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChainCreate) OnConflict(opts ...sql.ConflictOption) *ChainUpsertOne {
	_c.conflict = opts
	return &ChainUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Chain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChainCreate) OnConflictColumns(columns ...string) *ChainUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChainUpsertOne{
		create: _c,
	}
}

type (
	// ChainUpsertOne is the builder for "upsert"-ing
	//  one Chain node.
	ChainUpsertOne struct {
		create *ChainCreate
	}

	// ChainUpsert is the "OnConflict" setter.
	ChainUpsert struct {
		*sql.UpdateSet
	}
)

// SetChainID sets the "chain_id" field.
func (u *ChainUpsert) SetChainID(v int) *ChainUpsert {
	u.Set(chain.FieldChainID, v)
	return u
}

// UpdateChainID sets the "chain_id" field to the value that was provided on create.
func (u *ChainUpsert) UpdateChainID() *ChainUpsert {
	u.SetExcluded(chain.FieldChainID)
	return u
}

// AddChainID adds v to the "chain_id" field.
func (u *ChainUpsert) AddChainID(v int) *ChainUpsert {
	u.Add(chain.FieldChainID, v)
	return u
}

// SetName sets the "name" field.
func (u *ChainUpsert) SetName(v string) *ChainUpsert {
	u.Set(chain.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChainUpsert) UpdateName() *ChainUpsert {
	u.SetExcluded(chain.FieldName)
	return u
}

// SetNativeSymbol sets the "native_symbol" field.
func (u *ChainUpsert) SetNativeSymbol(v string) *ChainUpsert {
	u.Set(chain.FieldNativeSymbol, v)
	return u
}

// UpdateNativeSymbol sets the "native_symbol" field to the value that was provided on create.
func (u *ChainUpsert) UpdateNativeSymbol() *ChainUpsert {
	u.SetExcluded(chain.FieldNativeSymbol)
	return u
}

// SetConfirmations sets the "confirmations" field.
func (u *ChainUpsert) SetConfirmations(v int) *ChainUpsert {
	u.Set(chain.FieldConfirmations, v)
	return u
}

// UpdateConfirmations sets the "confirmations" field to the value that was provided on create.
func (u *ChainUpsert) UpdateConfirmations() *ChainUpsert {
	u.SetExcluded(chain.FieldConfirmations)
	return u
}

// AddConfirmations adds v to the "confirmations" field.
func (u *ChainUpsert) AddConfirmations(v int) *ChainUpsert {
	u.Add(chain.FieldConfirmations, v)
	return u
}

// SetScanBatchSize sets the "scan_batch_size" field.
func (u *ChainUpsert) SetScanBatchSize(v int) *ChainUpsert {
	u.Set(chain.FieldScanBatchSize, v)
	return u
}

// UpdateScanBatchSize sets the "scan_batch_size" field to the value that was provided on create.
func (u *ChainUpsert) UpdateScanBatchSize() *ChainUpsert {
	u.SetExcluded(chain.FieldScanBatchSize)
	return u
}

// AddScanBatchSize adds v to the "scan_batch_size" field.
func (u *ChainUpsert) AddScanBatchSize(v int) *ChainUpsert {
	u.Add(chain.FieldScanBatchSize, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ChainUpsert) SetStatus(v int8) *ChainUpsert {
	u.Set(chain.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChainUpsert) UpdateStatus() *ChainUpsert {
	u.SetExcluded(chain.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *ChainUpsert) AddStatus(v int8) *ChainUpsert {
	u.Add(chain.FieldStatus, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChainUpsert) SetUpdatedAt(v time.Time) *ChainUpsert {
	u.Set(chain.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChainUpsert) UpdateUpdatedAt() *ChainUpsert {
	u.SetExcluded(chain.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Chain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(chain.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChainUpsertOne) UpdateNewValues() *ChainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(chain.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chain.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Chain.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChainUpsertOne) Ignore() *ChainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChainUpsertOne) DoNothing() *ChainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChainCreate.OnConflict
// documentation for more info.
func (u *ChainUpsertOne) Update(set func(*ChainUpsert)) *ChainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChainUpsert{UpdateSet: update})
	}))
	return u
}

// SetChainID sets the "chain_id" field.
func (u *ChainUpsertOne) SetChainID(v int) *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.SetChainID(v)
	})
}

// AddChainID adds v to the "chain_id" field.
func (u *ChainUpsertOne) AddChainID(v int) *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.AddChainID(v)
	})
}

// UpdateChainID sets the "chain_id" field to the value that was provided on create.
func (u *ChainUpsertOne) UpdateChainID() *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateChainID()
	})
}

// SetName sets the "name" field.
func (u *ChainUpsertOne) SetName(v string) *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChainUpsertOne) UpdateName() *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateName()
	})
}

// SetNativeSymbol sets the "native_symbol" field.
func (u *ChainUpsertOne) SetNativeSymbol(v string) *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.SetNativeSymbol(v)
	})
}

// UpdateNativeSymbol sets the "native_symbol" field to the value that was provided on create.
func (u *ChainUpsertOne) UpdateNativeSymbol() *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateNativeSymbol()
	})
}

// SetConfirmations sets the "confirmations" field.
func (u *ChainUpsertOne) SetConfirmations(v int) *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.SetConfirmations(v)
	})
}

// AddConfirmations adds v to the "confirmations" field.
func (u *ChainUpsertOne) AddConfirmations(v int) *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.AddConfirmations(v)
	})
}

// UpdateConfirmations sets the "confirmations" field to the value that was provided on create.
func (u *ChainUpsertOne) UpdateConfirmations() *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateConfirmations()
	})
}

// SetScanBatchSize sets the "scan_batch_size" field.
func (u *ChainUpsertOne) SetScanBatchSize(v int) *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.SetScanBatchSize(v)
	})
}

// AddScanBatchSize adds v to the "scan_batch_size" field.
func (u *ChainUpsertOne) AddScanBatchSize(v int) *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.AddScanBatchSize(v)
	})
}

// UpdateScanBatchSize sets the "scan_batch_size" field to the value that was provided on create.
func (u *ChainUpsertOne) UpdateScanBatchSize() *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateScanBatchSize()
	})
}

// SetStatus sets the "status" field.
func (u *ChainUpsertOne) SetStatus(v int8) *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *ChainUpsertOne) AddStatus(v int8) *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChainUpsertOne) UpdateStatus() *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChainUpsertOne) SetUpdatedAt(v time.Time) *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChainUpsertOne) UpdateUpdatedAt() *ChainUpsertOne {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChainUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChainCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChainUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChainUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ChainUpsertOne.ID is not supported by MySQL driver. Use ChainUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChainUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChainCreateBulk is the builder for creating many Chain entities in bulk.
type ChainCreateBulk struct {
	config
	err      error
	builders []*ChainCreate
	conflict []sql.ConflictOption
}

// Save creates the Chain entities in the database.
func (_c *ChainCreateBulk) Save(ctx context.Context) ([]*Chain, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Chain, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChainCreateBulk) SaveX(ctx context.Context) []*Chain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChainCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChainCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Chain.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChainUpsert) {
//			SetChainID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChainCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChainUpsertBulk {
	_c.conflict = opts
	return &ChainUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Chain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChainCreateBulk) OnConflictColumns(columns ...string) *ChainUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChainUpsertBulk{
		create: _c,
	}
}

// ChainUpsertBulk is the builder for "upsert"-ing
// a bulk of Chain nodes.
type ChainUpsertBulk struct {
	create *ChainCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Chain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(chain.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChainUpsertBulk) UpdateNewValues() *ChainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(chain.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chain.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Chain.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChainUpsertBulk) Ignore() *ChainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChainUpsertBulk) DoNothing() *ChainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChainCreateBulk.OnConflict
// documentation for more info.
func (u *ChainUpsertBulk) Update(set func(*ChainUpsert)) *ChainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChainUpsert{UpdateSet: update})
	}))
	return u
}

// SetChainID sets the "chain_id" field.
func (u *ChainUpsertBulk) SetChainID(v int) *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.SetChainID(v)
	})
}

// AddChainID adds v to the "chain_id" field.
func (u *ChainUpsertBulk) AddChainID(v int) *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.AddChainID(v)
	})
}

// UpdateChainID sets the "chain_id" field to the value that was provided on create.
func (u *ChainUpsertBulk) UpdateChainID() *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateChainID()
	})
}

// SetName sets the "name" field.
func (u *ChainUpsertBulk) SetName(v string) *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChainUpsertBulk) UpdateName() *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateName()
	})
}

// SetNativeSymbol sets the "native_symbol" field.
func (u *ChainUpsertBulk) SetNativeSymbol(v string) *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.SetNativeSymbol(v)
	})
}

// UpdateNativeSymbol sets the "native_symbol" field to the value that was provided on create.
func (u *ChainUpsertBulk) UpdateNativeSymbol() *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateNativeSymbol()
	})
}

// SetConfirmations sets the "confirmations" field.
func (u *ChainUpsertBulk) SetConfirmations(v int) *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.SetConfirmations(v)
	})
}

// AddConfirmations adds v to the "confirmations" field.
func (u *ChainUpsertBulk) AddConfirmations(v int) *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.AddConfirmations(v)
	})
}

// UpdateConfirmations sets the "confirmations" field to the value that was provided on create.
func (u *ChainUpsertBulk) UpdateConfirmations() *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateConfirmations()
	})
}

// SetScanBatchSize sets the "scan_batch_size" field.
func (u *ChainUpsertBulk) SetScanBatchSize(v int) *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.SetScanBatchSize(v)
	})
}

// AddScanBatchSize adds v to the "scan_batch_size" field.
func (u *ChainUpsertBulk) AddScanBatchSize(v int) *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.AddScanBatchSize(v)
	})
}

// UpdateScanBatchSize sets the "scan_batch_size" field to the value that was provided on create.
func (u *ChainUpsertBulk) UpdateScanBatchSize() *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateScanBatchSize()
	})
}

// SetStatus sets the "status" field.
func (u *ChainUpsertBulk) SetStatus(v int8) *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *ChainUpsertBulk) AddStatus(v int8) *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChainUpsertBulk) UpdateStatus() *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChainUpsertBulk) SetUpdatedAt(v time.Time) *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChainUpsertBulk) UpdateUpdatedAt() *ChainUpsertBulk {
	return u.Update(func(s *ChainUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChainUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChainCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChainCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChainUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
