// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nexus-chain/ent/chainnode"
	"nexus-chain/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChainNodeUpdate is the builder for updating ChainNode entities.
type ChainNodeUpdate struct {
	config
	hooks     []Hook
	mutation  *ChainNodeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ChainNodeUpdate builder.
func (_u *ChainNodeUpdate) Where(ps ...predicate.ChainNode) *ChainNodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChainID sets the "chain_id" field.
func (_u *ChainNodeUpdate) SetChainID(v int) *ChainNodeUpdate {
	_u.mutation.ResetChainID()
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *ChainNodeUpdate) SetNillableChainID(v *int) *ChainNodeUpdate {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// AddChainID adds value to the "chain_id" field.
func (_u *ChainNodeUpdate) AddChainID(v int) *ChainNodeUpdate {
	_u.mutation.AddChainID(v)
	return _u
}

// SetNodeType sets the "node_type" field.
func (_u *ChainNodeUpdate) SetNodeType(v string) *ChainNodeUpdate {
	_u.mutation.SetNodeType(v)
	return _u
}

// SetNillableNodeType sets the "node_type" field if the given value is not nil.
func (_u *ChainNodeUpdate) SetNillableNodeType(v *string) *ChainNodeUpdate {
	if v != nil {
		_u.SetNodeType(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ChainNodeUpdate) SetName(v string) *ChainNodeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChainNodeUpdate) SetNillableName(v *string) *ChainNodeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *ChainNodeUpdate) SetURL(v string) *ChainNodeUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ChainNodeUpdate) SetNillableURL(v *string) *ChainNodeUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ChainNodeUpdate) SetPriority(v int) *ChainNodeUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ChainNodeUpdate) SetNillablePriority(v *int) *ChainNodeUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ChainNodeUpdate) AddPriority(v int) *ChainNodeUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChainNodeUpdate) SetStatus(v int8) *ChainNodeUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChainNodeUpdate) SetNillableStatus(v *int8) *ChainNodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ChainNodeUpdate) AddStatus(v int8) *ChainNodeUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChainNodeUpdate) SetUpdatedAt(v time.Time) *ChainNodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ChainNodeMutation object of the builder.
func (_u *ChainNodeUpdate) Mutation() *ChainNodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChainNodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChainNodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChainNodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChainNodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChainNodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chainnode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChainNodeUpdate) check() error {
	if v, ok := _u.mutation.NodeType(); ok {
		if err := chainnode.NodeTypeValidator(v); err != nil {
			return &ValidationError{Name: "node_type", err: fmt.Errorf(`ent: validator failed for field "ChainNode.node_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := chainnode.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChainNode.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := chainnode.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "ChainNode.url": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChainNodeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChainNodeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChainNodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chainnode.Table, chainnode.Columns, sqlgraph.NewFieldSpec(chainnode.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChainID(); ok {
		_spec.SetField(chainnode.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChainID(); ok {
		_spec.AddField(chainnode.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NodeType(); ok {
		_spec.SetField(chainnode.FieldNodeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(chainnode.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(chainnode.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(chainnode.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(chainnode.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(chainnode.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(chainnode.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chainnode.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chainnode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChainNodeUpdateOne is the builder for updating a single ChainNode entity.
type ChainNodeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ChainNodeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetChainID sets the "chain_id" field.
func (_u *ChainNodeUpdateOne) SetChainID(v int) *ChainNodeUpdateOne {
	_u.mutation.ResetChainID()
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *ChainNodeUpdateOne) SetNillableChainID(v *int) *ChainNodeUpdateOne {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// AddChainID adds value to the "chain_id" field.
func (_u *ChainNodeUpdateOne) AddChainID(v int) *ChainNodeUpdateOne {
	_u.mutation.AddChainID(v)
	return _u
}

// SetNodeType sets the "node_type" field.
func (_u *ChainNodeUpdateOne) SetNodeType(v string) *ChainNodeUpdateOne {
	_u.mutation.SetNodeType(v)
	return _u
}

// SetNillableNodeType sets the "node_type" field if the given value is not nil.
func (_u *ChainNodeUpdateOne) SetNillableNodeType(v *string) *ChainNodeUpdateOne {
	if v != nil {
		_u.SetNodeType(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ChainNodeUpdateOne) SetName(v string) *ChainNodeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChainNodeUpdateOne) SetNillableName(v *string) *ChainNodeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *ChainNodeUpdateOne) SetURL(v string) *ChainNodeUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ChainNodeUpdateOne) SetNillableURL(v *string) *ChainNodeUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ChainNodeUpdateOne) SetPriority(v int) *ChainNodeUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ChainNodeUpdateOne) SetNillablePriority(v *int) *ChainNodeUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ChainNodeUpdateOne) AddPriority(v int) *ChainNodeUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChainNodeUpdateOne) SetStatus(v int8) *ChainNodeUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChainNodeUpdateOne) SetNillableStatus(v *int8) *ChainNodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ChainNodeUpdateOne) AddStatus(v int8) *ChainNodeUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChainNodeUpdateOne) SetUpdatedAt(v time.Time) *ChainNodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ChainNodeMutation object of the builder.
func (_u *ChainNodeUpdateOne) Mutation() *ChainNodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChainNodeUpdate builder.
func (_u *ChainNodeUpdateOne) Where(ps ...predicate.ChainNode) *ChainNodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChainNodeUpdateOne) Select(field string, fields ...string) *ChainNodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChainNode entity.
func (_u *ChainNodeUpdateOne) Save(ctx context.Context) (*ChainNode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChainNodeUpdateOne) SaveX(ctx context.Context) *ChainNode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChainNodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChainNodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChainNodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chainnode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChainNodeUpdateOne) check() error {
	if v, ok := _u.mutation.NodeType(); ok {
		if err := chainnode.NodeTypeValidator(v); err != nil {
			return &ValidationError{Name: "node_type", err: fmt.Errorf(`ent: validator failed for field "ChainNode.node_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := chainnode.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChainNode.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := chainnode.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "ChainNode.url": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChainNodeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChainNodeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChainNodeUpdateOne) sqlSave(ctx context.Context) (_node *ChainNode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chainnode.Table, chainnode.Columns, sqlgraph.NewFieldSpec(chainnode.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChainNode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chainnode.FieldID)
		for _, f := range fields {
			if !chainnode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chainnode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChainID(); ok {
		_spec.SetField(chainnode.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChainID(); ok {
		_spec.AddField(chainnode.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NodeType(); ok {
		_spec.SetField(chainnode.FieldNodeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(chainnode.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(chainnode.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(chainnode.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(chainnode.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(chainnode.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(chainnode.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chainnode.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ChainNode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chainnode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
