// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nexus-chain/ent/chain"
	"nexus-chain/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChainUpdate is the builder for updating Chain entities.
type ChainUpdate struct {
	config
	hooks     []Hook
	mutation  *ChainMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ChainUpdate builder.
func (_u *ChainUpdate) Where(ps ...predicate.Chain) *ChainUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChainID sets the "chain_id" field.
func (_u *ChainUpdate) SetChainID(v int) *ChainUpdate {
	_u.mutation.ResetChainID()
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *ChainUpdate) SetNillableChainID(v *int) *ChainUpdate {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// AddChainID adds value to the "chain_id" field.
func (_u *ChainUpdate) AddChainID(v int) *ChainUpdate {
	_u.mutation.AddChainID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ChainUpdate) SetName(v string) *ChainUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChainUpdate) SetNillableName(v *string) *ChainUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNativeSymbol sets the "native_symbol" field.
func (_u *ChainUpdate) SetNativeSymbol(v string) *ChainUpdate {
	_u.mutation.SetNativeSymbol(v)
	return _u
}

// SetNillableNativeSymbol sets the "native_symbol" field if the given value is not nil.
func (_u *ChainUpdate) SetNillableNativeSymbol(v *string) *ChainUpdate {
	if v != nil {
		_u.SetNativeSymbol(*v)
	}
	return _u
}

// SetConfirmations sets the "confirmations" field.
func (_u *ChainUpdate) SetConfirmations(v int) *ChainUpdate {
	_u.mutation.ResetConfirmations()
	_u.mutation.SetConfirmations(v)
	return _u
}

// SetNillableConfirmations sets the "confirmations" field if the given value is not nil.
func (_u *ChainUpdate) SetNillableConfirmations(v *int) *ChainUpdate {
	if v != nil {
		_u.SetConfirmations(*v)
	}
	return _u
}

// AddConfirmations adds value to the "confirmations" field.
func (_u *ChainUpdate) AddConfirmations(v int) *ChainUpdate {
	_u.mutation.AddConfirmations(v)
	return _u
}

// SetScanBatchSize sets the "scan_batch_size" field.
func (_u *ChainUpdate) SetScanBatchSize(v int) *ChainUpdate {
	_u.mutation.ResetScanBatchSize()
	_u.mutation.SetScanBatchSize(v)
	return _u
}

// SetNillableScanBatchSize sets the "scan_batch_size" field if the given value is not nil.
func (_u *ChainUpdate) SetNillableScanBatchSize(v *int) *ChainUpdate {
	if v != nil {
		_u.SetScanBatchSize(*v)
	}
	return _u
}

// AddScanBatchSize adds value to the "scan_batch_size" field.
func (_u *ChainUpdate) AddScanBatchSize(v int) *ChainUpdate {
	_u.mutation.AddScanBatchSize(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChainUpdate) SetStatus(v int8) *ChainUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChainUpdate) SetNillableStatus(v *int8) *ChainUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ChainUpdate) AddStatus(v int8) *ChainUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChainUpdate) SetUpdatedAt(v time.Time) *ChainUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ChainMutation object of the builder.
func (_u *ChainUpdate) Mutation() *ChainMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChainUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChainUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChainUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChainUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChainUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChainUpdate) check() error {
	if v, ok := _u.mutation.ChainID(); ok {
		if err := chain.ChainIDValidator(v); err != nil {
			return &ValidationError{Name: "chain_id", err: fmt.Errorf(`ent: validator failed for field "Chain.chain_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := chain.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Chain.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NativeSymbol(); ok {
		if err := chain.NativeSymbolValidator(v); err != nil {
			return &ValidationError{Name: "native_symbol", err: fmt.Errorf(`ent: validator failed for field "Chain.native_symbol": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChainUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChainUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChainUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chain.Table, chain.Columns, sqlgraph.NewFieldSpec(chain.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChainID(); ok {
		_spec.SetField(chain.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChainID(); ok {
		_spec.AddField(chain.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(chain.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NativeSymbol(); ok {
		_spec.SetField(chain.FieldNativeSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confirmations(); ok {
		_spec.SetField(chain.FieldConfirmations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConfirmations(); ok {
		_spec.AddField(chain.FieldConfirmations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ScanBatchSize(); ok {
		_spec.SetField(chain.FieldScanBatchSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScanBatchSize(); ok {
		_spec.AddField(chain.FieldScanBatchSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(chain.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(chain.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chain.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChainUpdateOne is the builder for updating a single Chain entity.
type ChainUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ChainMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetChainID sets the "chain_id" field.
func (_u *ChainUpdateOne) SetChainID(v int) *ChainUpdateOne {
	_u.mutation.ResetChainID()
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *ChainUpdateOne) SetNillableChainID(v *int) *ChainUpdateOne {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// AddChainID adds value to the "chain_id" field.
func (_u *ChainUpdateOne) AddChainID(v int) *ChainUpdateOne {
	_u.mutation.AddChainID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ChainUpdateOne) SetName(v string) *ChainUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChainUpdateOne) SetNillableName(v *string) *ChainUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNativeSymbol sets the "native_symbol" field.
func (_u *ChainUpdateOne) SetNativeSymbol(v string) *ChainUpdateOne {
	_u.mutation.SetNativeSymbol(v)
	return _u
}

// SetNillableNativeSymbol sets the "native_symbol" field if the given value is not nil.
func (_u *ChainUpdateOne) SetNillableNativeSymbol(v *string) *ChainUpdateOne {
	if v != nil {
		_u.SetNativeSymbol(*v)
	}
	return _u
}

// SetConfirmations sets the "confirmations" field.
func (_u *ChainUpdateOne) SetConfirmations(v int) *ChainUpdateOne {
	_u.mutation.ResetConfirmations()
	_u.mutation.SetConfirmations(v)
	return _u
}

// SetNillableConfirmations sets the "confirmations" field if the given value is not nil.
func (_u *ChainUpdateOne) SetNillableConfirmations(v *int) *ChainUpdateOne {
	if v != nil {
		_u.SetConfirmations(*v)
	}
	return _u
}

// AddConfirmations adds value to the "confirmations" field.
func (_u *ChainUpdateOne) AddConfirmations(v int) *ChainUpdateOne {
	_u.mutation.AddConfirmations(v)
	return _u
}

// SetScanBatchSize sets the "scan_batch_size" field.
func (_u *ChainUpdateOne) SetScanBatchSize(v int) *ChainUpdateOne {
	_u.mutation.ResetScanBatchSize()
	_u.mutation.SetScanBatchSize(v)
	return _u
}

// SetNillableScanBatchSize sets the "scan_batch_size" field if the given value is not nil.
func (_u *ChainUpdateOne) SetNillableScanBatchSize(v *int) *ChainUpdateOne {
	if v != nil {
		_u.SetScanBatchSize(*v)
	}
	return _u
}

// AddScanBatchSize adds value to the "scan_batch_size" field.
func (_u *ChainUpdateOne) AddScanBatchSize(v int) *ChainUpdateOne {
	_u.mutation.AddScanBatchSize(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChainUpdateOne) SetStatus(v int8) *ChainUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChainUpdateOne) SetNillableStatus(v *int8) *ChainUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ChainUpdateOne) AddStatus(v int8) *ChainUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChainUpdateOne) SetUpdatedAt(v time.Time) *ChainUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ChainMutation object of the builder.
func (_u *ChainUpdateOne) Mutation() *ChainMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChainUpdate builder.
func (_u *ChainUpdateOne) Where(ps ...predicate.Chain) *ChainUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChainUpdateOne) Select(field string, fields ...string) *ChainUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Chain entity.
func (_u *ChainUpdateOne) Save(ctx context.Context) (*Chain, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChainUpdateOne) SaveX(ctx context.Context) *Chain {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChainUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChainUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChainUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChainUpdateOne) check() error {
	if v, ok := _u.mutation.ChainID(); ok {
		if err := chain.ChainIDValidator(v); err != nil {
			return &ValidationError{Name: "chain_id", err: fmt.Errorf(`ent: validator failed for field "Chain.chain_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := chain.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Chain.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NativeSymbol(); ok {
		if err := chain.NativeSymbolValidator(v); err != nil {
			return &ValidationError{Name: "native_symbol", err: fmt.Errorf(`ent: validator failed for field "Chain.native_symbol": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChainUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChainUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChainUpdateOne) sqlSave(ctx context.Context) (_node *Chain, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chain.Table, chain.Columns, sqlgraph.NewFieldSpec(chain.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chain.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chain.FieldID)
		for _, f := range fields {
			if !chain.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChainID(); ok {
		_spec.SetField(chain.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChainID(); ok {
		_spec.AddField(chain.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(chain.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NativeSymbol(); ok {
		_spec.SetField(chain.FieldNativeSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confirmations(); ok {
		_spec.SetField(chain.FieldConfirmations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConfirmations(); ok {
		_spec.AddField(chain.FieldConfirmations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ScanBatchSize(); ok {
		_spec.SetField(chain.FieldScanBatchSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScanBatchSize(); ok {
		_spec.AddField(chain.FieldScanBatchSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(chain.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(chain.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chain.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Chain{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
