// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"nexus-chain/ent/migrate"

	"nexus-chain/ent/monitorcontract"
	"nexus-chain/ent/monitorevent"
	"nexus-chain/ent/parsedeventslog"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// MonitorContract is the client for interacting with the MonitorContract builders.
	MonitorContract *MonitorContractClient
	// MonitorEvent is the client for interacting with the MonitorEvent builders.
	MonitorEvent *MonitorEventClient
	// ParsedEventsLog is the client for interacting with the ParsedEventsLog builders.
	ParsedEventsLog *ParsedEventsLogClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.MonitorContract = NewMonitorContractClient(c.config)
	c.MonitorEvent = NewMonitorEventClient(c.config)
	c.ParsedEventsLog = NewParsedEventsLogClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		MonitorContract: NewMonitorContractClient(cfg),
		MonitorEvent:    NewMonitorEventClient(cfg),
		ParsedEventsLog: NewParsedEventsLogClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		MonitorContract: NewMonitorContractClient(cfg),
		MonitorEvent:    NewMonitorEventClient(cfg),
		ParsedEventsLog: NewParsedEventsLogClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		MonitorContract.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.MonitorContract.Use(hooks...)
	c.MonitorEvent.Use(hooks...)
	c.ParsedEventsLog.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.MonitorContract.Intercept(interceptors...)
	c.MonitorEvent.Intercept(interceptors...)
	c.ParsedEventsLog.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *MonitorContractMutation:
		return c.MonitorContract.mutate(ctx, m)
	case *MonitorEventMutation:
		return c.MonitorEvent.mutate(ctx, m)
	case *ParsedEventsLogMutation:
		return c.ParsedEventsLog.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// MonitorContractClient is a client for the MonitorContract schema.
type MonitorContractClient struct {
	config
}

// NewMonitorContractClient returns a client for the MonitorContract from the given config.
func NewMonitorContractClient(c config) *MonitorContractClient {
	return &MonitorContractClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `monitorcontract.Hooks(f(g(h())))`.
func (c *MonitorContractClient) Use(hooks ...Hook) {
	c.hooks.MonitorContract = append(c.hooks.MonitorContract, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `monitorcontract.Intercept(f(g(h())))`.
func (c *MonitorContractClient) Intercept(interceptors ...Interceptor) {
	c.inters.MonitorContract = append(c.inters.MonitorContract, interceptors...)
}

// Create returns a builder for creating a MonitorContract entity.
func (c *MonitorContractClient) Create() *MonitorContractCreate {
	mutation := newMonitorContractMutation(c.config, OpCreate)
	return &MonitorContractCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MonitorContract entities.
func (c *MonitorContractClient) CreateBulk(builders ...*MonitorContractCreate) *MonitorContractCreateBulk {
	return &MonitorContractCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MonitorContractClient) MapCreateBulk(slice any, setFunc func(*MonitorContractCreate, int)) *MonitorContractCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MonitorContractCreateBulk{err: fmt.Errorf("calling to MonitorContractClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MonitorContractCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MonitorContractCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MonitorContract.
func (c *MonitorContractClient) Update() *MonitorContractUpdate {
	mutation := newMonitorContractMutation(c.config, OpUpdate)
	return &MonitorContractUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MonitorContractClient) UpdateOne(_m *MonitorContract) *MonitorContractUpdateOne {
	mutation := newMonitorContractMutation(c.config, OpUpdateOne, withMonitorContract(_m))
	return &MonitorContractUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MonitorContractClient) UpdateOneID(id uuid.UUID) *MonitorContractUpdateOne {
	mutation := newMonitorContractMutation(c.config, OpUpdateOne, withMonitorContractID(id))
	return &MonitorContractUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MonitorContract.
func (c *MonitorContractClient) Delete() *MonitorContractDelete {
	mutation := newMonitorContractMutation(c.config, OpDelete)
	return &MonitorContractDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MonitorContractClient) DeleteOne(_m *MonitorContract) *MonitorContractDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MonitorContractClient) DeleteOneID(id uuid.UUID) *MonitorContractDeleteOne {
	builder := c.Delete().Where(monitorcontract.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MonitorContractDeleteOne{builder}
}

// Query returns a query builder for MonitorContract.
func (c *MonitorContractClient) Query() *MonitorContractQuery {
	return &MonitorContractQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMonitorContract},
		inters: c.Interceptors(),
	}
}

// Get returns a MonitorContract entity by its id.
func (c *MonitorContractClient) Get(ctx context.Context, id uuid.UUID) (*MonitorContract, error) {
	return c.Query().Where(monitorcontract.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MonitorContractClient) GetX(ctx context.Context, id uuid.UUID) *MonitorContract {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MonitorContractClient) Hooks() []Hook {
	return c.hooks.MonitorContract
}

// Interceptors returns the client interceptors.
func (c *MonitorContractClient) Interceptors() []Interceptor {
	return c.inters.MonitorContract
}

func (c *MonitorContractClient) mutate(ctx context.Context, m *MonitorContractMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MonitorContractCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MonitorContractUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MonitorContractUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MonitorContractDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MonitorContract mutation op: %q", m.Op())
	}
}

// MonitorEventClient is a client for the MonitorEvent schema.
type MonitorEventClient struct {
	config
}

// NewMonitorEventClient returns a client for the MonitorEvent from the given config.
func NewMonitorEventClient(c config) *MonitorEventClient {
	return &MonitorEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `monitorevent.Hooks(f(g(h())))`.
func (c *MonitorEventClient) Use(hooks ...Hook) {
	c.hooks.MonitorEvent = append(c.hooks.MonitorEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `monitorevent.Intercept(f(g(h())))`.
func (c *MonitorEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.MonitorEvent = append(c.inters.MonitorEvent, interceptors...)
}

// Create returns a builder for creating a MonitorEvent entity.
func (c *MonitorEventClient) Create() *MonitorEventCreate {
	mutation := newMonitorEventMutation(c.config, OpCreate)
	return &MonitorEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MonitorEvent entities.
func (c *MonitorEventClient) CreateBulk(builders ...*MonitorEventCreate) *MonitorEventCreateBulk {
	return &MonitorEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MonitorEventClient) MapCreateBulk(slice any, setFunc func(*MonitorEventCreate, int)) *MonitorEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MonitorEventCreateBulk{err: fmt.Errorf("calling to MonitorEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MonitorEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MonitorEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MonitorEvent.
func (c *MonitorEventClient) Update() *MonitorEventUpdate {
	mutation := newMonitorEventMutation(c.config, OpUpdate)
	return &MonitorEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MonitorEventClient) UpdateOne(_m *MonitorEvent) *MonitorEventUpdateOne {
	mutation := newMonitorEventMutation(c.config, OpUpdateOne, withMonitorEvent(_m))
	return &MonitorEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MonitorEventClient) UpdateOneID(id uuid.UUID) *MonitorEventUpdateOne {
	mutation := newMonitorEventMutation(c.config, OpUpdateOne, withMonitorEventID(id))
	return &MonitorEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MonitorEvent.
func (c *MonitorEventClient) Delete() *MonitorEventDelete {
	mutation := newMonitorEventMutation(c.config, OpDelete)
	return &MonitorEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MonitorEventClient) DeleteOne(_m *MonitorEvent) *MonitorEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MonitorEventClient) DeleteOneID(id uuid.UUID) *MonitorEventDeleteOne {
	builder := c.Delete().Where(monitorevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MonitorEventDeleteOne{builder}
}

// Query returns a query builder for MonitorEvent.
func (c *MonitorEventClient) Query() *MonitorEventQuery {
	return &MonitorEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMonitorEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a MonitorEvent entity by its id.
func (c *MonitorEventClient) Get(ctx context.Context, id uuid.UUID) (*MonitorEvent, error) {
	return c.Query().Where(monitorevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MonitorEventClient) GetX(ctx context.Context, id uuid.UUID) *MonitorEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MonitorEventClient) Hooks() []Hook {
	return c.hooks.MonitorEvent
}

// Interceptors returns the client interceptors.
func (c *MonitorEventClient) Interceptors() []Interceptor {
	return c.inters.MonitorEvent
}

func (c *MonitorEventClient) mutate(ctx context.Context, m *MonitorEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MonitorEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MonitorEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MonitorEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MonitorEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MonitorEvent mutation op: %q", m.Op())
	}
}

// ParsedEventsLogClient is a client for the ParsedEventsLog schema.
type ParsedEventsLogClient struct {
	config
}

// NewParsedEventsLogClient returns a client for the ParsedEventsLog from the given config.
func NewParsedEventsLogClient(c config) *ParsedEventsLogClient {
	return &ParsedEventsLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `parsedeventslog.Hooks(f(g(h())))`.
func (c *ParsedEventsLogClient) Use(hooks ...Hook) {
	c.hooks.ParsedEventsLog = append(c.hooks.ParsedEventsLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `parsedeventslog.Intercept(f(g(h())))`.
func (c *ParsedEventsLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.ParsedEventsLog = append(c.inters.ParsedEventsLog, interceptors...)
}

// Create returns a builder for creating a ParsedEventsLog entity.
func (c *ParsedEventsLogClient) Create() *ParsedEventsLogCreate {
	mutation := newParsedEventsLogMutation(c.config, OpCreate)
	return &ParsedEventsLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ParsedEventsLog entities.
func (c *ParsedEventsLogClient) CreateBulk(builders ...*ParsedEventsLogCreate) *ParsedEventsLogCreateBulk {
	return &ParsedEventsLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ParsedEventsLogClient) MapCreateBulk(slice any, setFunc func(*ParsedEventsLogCreate, int)) *ParsedEventsLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ParsedEventsLogCreateBulk{err: fmt.Errorf("calling to ParsedEventsLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ParsedEventsLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ParsedEventsLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ParsedEventsLog.
func (c *ParsedEventsLogClient) Update() *ParsedEventsLogUpdate {
	mutation := newParsedEventsLogMutation(c.config, OpUpdate)
	return &ParsedEventsLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ParsedEventsLogClient) UpdateOne(_m *ParsedEventsLog) *ParsedEventsLogUpdateOne {
	mutation := newParsedEventsLogMutation(c.config, OpUpdateOne, withParsedEventsLog(_m))
	return &ParsedEventsLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ParsedEventsLogClient) UpdateOneID(id uuid.UUID) *ParsedEventsLogUpdateOne {
	mutation := newParsedEventsLogMutation(c.config, OpUpdateOne, withParsedEventsLogID(id))
	return &ParsedEventsLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ParsedEventsLog.
func (c *ParsedEventsLogClient) Delete() *ParsedEventsLogDelete {
	mutation := newParsedEventsLogMutation(c.config, OpDelete)
	return &ParsedEventsLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ParsedEventsLogClient) DeleteOne(_m *ParsedEventsLog) *ParsedEventsLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ParsedEventsLogClient) DeleteOneID(id uuid.UUID) *ParsedEventsLogDeleteOne {
	builder := c.Delete().Where(parsedeventslog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ParsedEventsLogDeleteOne{builder}
}

// Query returns a query builder for ParsedEventsLog.
func (c *ParsedEventsLogClient) Query() *ParsedEventsLogQuery {
	return &ParsedEventsLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeParsedEventsLog},
		inters: c.Interceptors(),
	}
}

// Get returns a ParsedEventsLog entity by its id.
func (c *ParsedEventsLogClient) Get(ctx context.Context, id uuid.UUID) (*ParsedEventsLog, error) {
	return c.Query().Where(parsedeventslog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ParsedEventsLogClient) GetX(ctx context.Context, id uuid.UUID) *ParsedEventsLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ParsedEventsLogClient) Hooks() []Hook {
	return c.hooks.ParsedEventsLog
}

// Interceptors returns the client interceptors.
func (c *ParsedEventsLogClient) Interceptors() []Interceptor {
	return c.inters.ParsedEventsLog
}

func (c *ParsedEventsLogClient) mutate(ctx context.Context, m *ParsedEventsLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ParsedEventsLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ParsedEventsLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ParsedEventsLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ParsedEventsLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ParsedEventsLog mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		MonitorContract, MonitorEvent, ParsedEventsLog []ent.Hook
	}
	inters struct {
		MonitorContract, MonitorEvent, ParsedEventsLog []ent.Interceptor
	}
)
