// Code generated by ent, DO NOT EDIT.

package ent

import (
	"errors"
	"fmt"
	"nexus-chain/ent/monitorcontract"
	"nexus-chain/ent/monitorevent"
	"nexus-chain/ent/parsedeventslog"
	"nexus-chain/ent/predicate"
	"time"

	"github.com/google/uuid"
)

// MonitorContractWhereInput represents a where input for filtering MonitorContract queries.
type MonitorContractWhereInput struct {
	Predicates []predicate.MonitorContract  `json:"-"`
	Not        *MonitorContractWhereInput   `json:"not,omitempty"`
	Or         []*MonitorContractWhereInput `json:"or,omitempty"`
	And        []*MonitorContractWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *uuid.UUID  `json:"id,omitempty"`
	IDNEQ   *uuid.UUID  `json:"idNEQ,omitempty"`
	IDIn    []uuid.UUID `json:"idIn,omitempty"`
	IDNotIn []uuid.UUID `json:"idNotIn,omitempty"`
	IDGT    *uuid.UUID  `json:"idGT,omitempty"`
	IDGTE   *uuid.UUID  `json:"idGTE,omitempty"`
	IDLT    *uuid.UUID  `json:"idLT,omitempty"`
	IDLTE   *uuid.UUID  `json:"idLTE,omitempty"`

	// "chain_id" field predicates.
	ChainID      *int  `json:"chainID,omitempty"`
	ChainIDNEQ   *int  `json:"chainIDNEQ,omitempty"`
	ChainIDIn    []int `json:"chainIDIn,omitempty"`
	ChainIDNotIn []int `json:"chainIDNotIn,omitempty"`
	ChainIDGT    *int  `json:"chainIDGT,omitempty"`
	ChainIDGTE   *int  `json:"chainIDGTE,omitempty"`
	ChainIDLT    *int  `json:"chainIDLT,omitempty"`
	ChainIDLTE   *int  `json:"chainIDLTE,omitempty"`

	// "address" field predicates.
	Address             *string  `json:"address,omitempty"`
	AddressNEQ          *string  `json:"addressNEQ,omitempty"`
	AddressIn           []string `json:"addressIn,omitempty"`
	AddressNotIn        []string `json:"addressNotIn,omitempty"`
	AddressGT           *string  `json:"addressGT,omitempty"`
	AddressGTE          *string  `json:"addressGTE,omitempty"`
	AddressLT           *string  `json:"addressLT,omitempty"`
	AddressLTE          *string  `json:"addressLTE,omitempty"`
	AddressContains     *string  `json:"addressContains,omitempty"`
	AddressHasPrefix    *string  `json:"addressHasPrefix,omitempty"`
	AddressHasSuffix    *string  `json:"addressHasSuffix,omitempty"`
	AddressEqualFold    *string  `json:"addressEqualFold,omitempty"`
	AddressContainsFold *string  `json:"addressContainsFold,omitempty"`

	// "name" field predicates.
	Name             *string  `json:"name,omitempty"`
	NameNEQ          *string  `json:"nameNEQ,omitempty"`
	NameIn           []string `json:"nameIn,omitempty"`
	NameNotIn        []string `json:"nameNotIn,omitempty"`
	NameGT           *string  `json:"nameGT,omitempty"`
	NameGTE          *string  `json:"nameGTE,omitempty"`
	NameLT           *string  `json:"nameLT,omitempty"`
	NameLTE          *string  `json:"nameLTE,omitempty"`
	NameContains     *string  `json:"nameContains,omitempty"`
	NameHasPrefix    *string  `json:"nameHasPrefix,omitempty"`
	NameHasSuffix    *string  `json:"nameHasSuffix,omitempty"`
	NameEqualFold    *string  `json:"nameEqualFold,omitempty"`
	NameContainsFold *string  `json:"nameContainsFold,omitempty"`

	// "status" field predicates.
	Status      *int8  `json:"status,omitempty"`
	StatusNEQ   *int8  `json:"statusNEQ,omitempty"`
	StatusIn    []int8 `json:"statusIn,omitempty"`
	StatusNotIn []int8 `json:"statusNotIn,omitempty"`
	StatusGT    *int8  `json:"statusGT,omitempty"`
	StatusGTE   *int8  `json:"statusGTE,omitempty"`
	StatusLT    *int8  `json:"statusLT,omitempty"`
	StatusLTE   *int8  `json:"statusLTE,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *MonitorContractWhereInput) AddPredicates(predicates ...predicate.MonitorContract) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the MonitorContractWhereInput filter on the MonitorContractQuery builder.
func (i *MonitorContractWhereInput) Filter(q *MonitorContractQuery) (*MonitorContractQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyMonitorContractWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyMonitorContractWhereInput is returned in case the MonitorContractWhereInput is empty.
var ErrEmptyMonitorContractWhereInput = errors.New("ent: empty predicate MonitorContractWhereInput")

// P returns a predicate for filtering monitorcontracts.
// An error is returned if the input is empty or invalid.
func (i *MonitorContractWhereInput) P() (predicate.MonitorContract, error) {
	var predicates []predicate.MonitorContract
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, monitorcontract.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.MonitorContract, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, monitorcontract.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.MonitorContract, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, monitorcontract.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, monitorcontract.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, monitorcontract.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, monitorcontract.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, monitorcontract.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, monitorcontract.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, monitorcontract.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, monitorcontract.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, monitorcontract.IDLTE(*i.IDLTE))
	}
	if i.ChainID != nil {
		predicates = append(predicates, monitorcontract.ChainIDEQ(*i.ChainID))
	}
	if i.ChainIDNEQ != nil {
		predicates = append(predicates, monitorcontract.ChainIDNEQ(*i.ChainIDNEQ))
	}
	if len(i.ChainIDIn) > 0 {
		predicates = append(predicates, monitorcontract.ChainIDIn(i.ChainIDIn...))
	}
	if len(i.ChainIDNotIn) > 0 {
		predicates = append(predicates, monitorcontract.ChainIDNotIn(i.ChainIDNotIn...))
	}
	if i.ChainIDGT != nil {
		predicates = append(predicates, monitorcontract.ChainIDGT(*i.ChainIDGT))
	}
	if i.ChainIDGTE != nil {
		predicates = append(predicates, monitorcontract.ChainIDGTE(*i.ChainIDGTE))
	}
	if i.ChainIDLT != nil {
		predicates = append(predicates, monitorcontract.ChainIDLT(*i.ChainIDLT))
	}
	if i.ChainIDLTE != nil {
		predicates = append(predicates, monitorcontract.ChainIDLTE(*i.ChainIDLTE))
	}
	if i.Address != nil {
		predicates = append(predicates, monitorcontract.AddressEQ(*i.Address))
	}
	if i.AddressNEQ != nil {
		predicates = append(predicates, monitorcontract.AddressNEQ(*i.AddressNEQ))
	}
	if len(i.AddressIn) > 0 {
		predicates = append(predicates, monitorcontract.AddressIn(i.AddressIn...))
	}
	if len(i.AddressNotIn) > 0 {
		predicates = append(predicates, monitorcontract.AddressNotIn(i.AddressNotIn...))
	}
	if i.AddressGT != nil {
		predicates = append(predicates, monitorcontract.AddressGT(*i.AddressGT))
	}
	if i.AddressGTE != nil {
		predicates = append(predicates, monitorcontract.AddressGTE(*i.AddressGTE))
	}
	if i.AddressLT != nil {
		predicates = append(predicates, monitorcontract.AddressLT(*i.AddressLT))
	}
	if i.AddressLTE != nil {
		predicates = append(predicates, monitorcontract.AddressLTE(*i.AddressLTE))
	}
	if i.AddressContains != nil {
		predicates = append(predicates, monitorcontract.AddressContains(*i.AddressContains))
	}
	if i.AddressHasPrefix != nil {
		predicates = append(predicates, monitorcontract.AddressHasPrefix(*i.AddressHasPrefix))
	}
	if i.AddressHasSuffix != nil {
		predicates = append(predicates, monitorcontract.AddressHasSuffix(*i.AddressHasSuffix))
	}
	if i.AddressEqualFold != nil {
		predicates = append(predicates, monitorcontract.AddressEqualFold(*i.AddressEqualFold))
	}
	if i.AddressContainsFold != nil {
		predicates = append(predicates, monitorcontract.AddressContainsFold(*i.AddressContainsFold))
	}
	if i.Name != nil {
		predicates = append(predicates, monitorcontract.NameEQ(*i.Name))
	}
	if i.NameNEQ != nil {
		predicates = append(predicates, monitorcontract.NameNEQ(*i.NameNEQ))
	}
	if len(i.NameIn) > 0 {
		predicates = append(predicates, monitorcontract.NameIn(i.NameIn...))
	}
	if len(i.NameNotIn) > 0 {
		predicates = append(predicates, monitorcontract.NameNotIn(i.NameNotIn...))
	}
	if i.NameGT != nil {
		predicates = append(predicates, monitorcontract.NameGT(*i.NameGT))
	}
	if i.NameGTE != nil {
		predicates = append(predicates, monitorcontract.NameGTE(*i.NameGTE))
	}
	if i.NameLT != nil {
		predicates = append(predicates, monitorcontract.NameLT(*i.NameLT))
	}
	if i.NameLTE != nil {
		predicates = append(predicates, monitorcontract.NameLTE(*i.NameLTE))
	}
	if i.NameContains != nil {
		predicates = append(predicates, monitorcontract.NameContains(*i.NameContains))
	}
	if i.NameHasPrefix != nil {
		predicates = append(predicates, monitorcontract.NameHasPrefix(*i.NameHasPrefix))
	}
	if i.NameHasSuffix != nil {
		predicates = append(predicates, monitorcontract.NameHasSuffix(*i.NameHasSuffix))
	}
	if i.NameEqualFold != nil {
		predicates = append(predicates, monitorcontract.NameEqualFold(*i.NameEqualFold))
	}
	if i.NameContainsFold != nil {
		predicates = append(predicates, monitorcontract.NameContainsFold(*i.NameContainsFold))
	}
	if i.Status != nil {
		predicates = append(predicates, monitorcontract.StatusEQ(*i.Status))
	}
	if i.StatusNEQ != nil {
		predicates = append(predicates, monitorcontract.StatusNEQ(*i.StatusNEQ))
	}
	if len(i.StatusIn) > 0 {
		predicates = append(predicates, monitorcontract.StatusIn(i.StatusIn...))
	}
	if len(i.StatusNotIn) > 0 {
		predicates = append(predicates, monitorcontract.StatusNotIn(i.StatusNotIn...))
	}
	if i.StatusGT != nil {
		predicates = append(predicates, monitorcontract.StatusGT(*i.StatusGT))
	}
	if i.StatusGTE != nil {
		predicates = append(predicates, monitorcontract.StatusGTE(*i.StatusGTE))
	}
	if i.StatusLT != nil {
		predicates = append(predicates, monitorcontract.StatusLT(*i.StatusLT))
	}
	if i.StatusLTE != nil {
		predicates = append(predicates, monitorcontract.StatusLTE(*i.StatusLTE))
	}

	switch len(predicates) {
	case 0:
		return nil, ErrEmptyMonitorContractWhereInput
	case 1:
		return predicates[0], nil
	default:
		return monitorcontract.And(predicates...), nil
	}
}

// MonitorEventWhereInput represents a where input for filtering MonitorEvent queries.
type MonitorEventWhereInput struct {
	Predicates []predicate.MonitorEvent  `json:"-"`
	Not        *MonitorEventWhereInput   `json:"not,omitempty"`
	Or         []*MonitorEventWhereInput `json:"or,omitempty"`
	And        []*MonitorEventWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *uuid.UUID  `json:"id,omitempty"`
	IDNEQ   *uuid.UUID  `json:"idNEQ,omitempty"`
	IDIn    []uuid.UUID `json:"idIn,omitempty"`
	IDNotIn []uuid.UUID `json:"idNotIn,omitempty"`
	IDGT    *uuid.UUID  `json:"idGT,omitempty"`
	IDGTE   *uuid.UUID  `json:"idGTE,omitempty"`
	IDLT    *uuid.UUID  `json:"idLT,omitempty"`
	IDLTE   *uuid.UUID  `json:"idLTE,omitempty"`

	// "contract_id" field predicates.
	ContractID      *uuid.UUID  `json:"contractID,omitempty"`
	ContractIDNEQ   *uuid.UUID  `json:"contractIDNEQ,omitempty"`
	ContractIDIn    []uuid.UUID `json:"contractIDIn,omitempty"`
	ContractIDNotIn []uuid.UUID `json:"contractIDNotIn,omitempty"`
	ContractIDGT    *uuid.UUID  `json:"contractIDGT,omitempty"`
	ContractIDGTE   *uuid.UUID  `json:"contractIDGTE,omitempty"`
	ContractIDLT    *uuid.UUID  `json:"contractIDLT,omitempty"`
	ContractIDLTE   *uuid.UUID  `json:"contractIDLTE,omitempty"`

	// "event_name" field predicates.
	EventName             *string  `json:"eventName,omitempty"`
	EventNameNEQ          *string  `json:"eventNameNEQ,omitempty"`
	EventNameIn           []string `json:"eventNameIn,omitempty"`
	EventNameNotIn        []string `json:"eventNameNotIn,omitempty"`
	EventNameGT           *string  `json:"eventNameGT,omitempty"`
	EventNameGTE          *string  `json:"eventNameGTE,omitempty"`
	EventNameLT           *string  `json:"eventNameLT,omitempty"`
	EventNameLTE          *string  `json:"eventNameLTE,omitempty"`
	EventNameContains     *string  `json:"eventNameContains,omitempty"`
	EventNameHasPrefix    *string  `json:"eventNameHasPrefix,omitempty"`
	EventNameHasSuffix    *string  `json:"eventNameHasSuffix,omitempty"`
	EventNameEqualFold    *string  `json:"eventNameEqualFold,omitempty"`
	EventNameContainsFold *string  `json:"eventNameContainsFold,omitempty"`

	// "mq_routing_key" field predicates.
	MqRoutingKey             *string  `json:"mqRoutingKey,omitempty"`
	MqRoutingKeyNEQ          *string  `json:"mqRoutingKeyNEQ,omitempty"`
	MqRoutingKeyIn           []string `json:"mqRoutingKeyIn,omitempty"`
	MqRoutingKeyNotIn        []string `json:"mqRoutingKeyNotIn,omitempty"`
	MqRoutingKeyGT           *string  `json:"mqRoutingKeyGT,omitempty"`
	MqRoutingKeyGTE          *string  `json:"mqRoutingKeyGTE,omitempty"`
	MqRoutingKeyLT           *string  `json:"mqRoutingKeyLT,omitempty"`
	MqRoutingKeyLTE          *string  `json:"mqRoutingKeyLTE,omitempty"`
	MqRoutingKeyContains     *string  `json:"mqRoutingKeyContains,omitempty"`
	MqRoutingKeyHasPrefix    *string  `json:"mqRoutingKeyHasPrefix,omitempty"`
	MqRoutingKeyHasSuffix    *string  `json:"mqRoutingKeyHasSuffix,omitempty"`
	MqRoutingKeyEqualFold    *string  `json:"mqRoutingKeyEqualFold,omitempty"`
	MqRoutingKeyContainsFold *string  `json:"mqRoutingKeyContainsFold,omitempty"`

	// "status" field predicates.
	Status      *int8  `json:"status,omitempty"`
	StatusNEQ   *int8  `json:"statusNEQ,omitempty"`
	StatusIn    []int8 `json:"statusIn,omitempty"`
	StatusNotIn []int8 `json:"statusNotIn,omitempty"`
	StatusGT    *int8  `json:"statusGT,omitempty"`
	StatusGTE   *int8  `json:"statusGTE,omitempty"`
	StatusLT    *int8  `json:"statusLT,omitempty"`
	StatusLTE   *int8  `json:"statusLTE,omitempty"`

	// "last_block" field predicates.
	LastBlock      *int64  `json:"lastBlock,omitempty"`
	LastBlockNEQ   *int64  `json:"lastBlockNEQ,omitempty"`
	LastBlockIn    []int64 `json:"lastBlockIn,omitempty"`
	LastBlockNotIn []int64 `json:"lastBlockNotIn,omitempty"`
	LastBlockGT    *int64  `json:"lastBlockGT,omitempty"`
	LastBlockGTE   *int64  `json:"lastBlockGTE,omitempty"`
	LastBlockLT    *int64  `json:"lastBlockLT,omitempty"`
	LastBlockLTE   *int64  `json:"lastBlockLTE,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *MonitorEventWhereInput) AddPredicates(predicates ...predicate.MonitorEvent) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the MonitorEventWhereInput filter on the MonitorEventQuery builder.
func (i *MonitorEventWhereInput) Filter(q *MonitorEventQuery) (*MonitorEventQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyMonitorEventWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyMonitorEventWhereInput is returned in case the MonitorEventWhereInput is empty.
var ErrEmptyMonitorEventWhereInput = errors.New("ent: empty predicate MonitorEventWhereInput")

// P returns a predicate for filtering monitorevents.
// An error is returned if the input is empty or invalid.
func (i *MonitorEventWhereInput) P() (predicate.MonitorEvent, error) {
	var predicates []predicate.MonitorEvent
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, monitorevent.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.MonitorEvent, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, monitorevent.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.MonitorEvent, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, monitorevent.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, monitorevent.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, monitorevent.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, monitorevent.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, monitorevent.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, monitorevent.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, monitorevent.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, monitorevent.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, monitorevent.IDLTE(*i.IDLTE))
	}
	if i.ContractID != nil {
		predicates = append(predicates, monitorevent.ContractIDEQ(*i.ContractID))
	}
	if i.ContractIDNEQ != nil {
		predicates = append(predicates, monitorevent.ContractIDNEQ(*i.ContractIDNEQ))
	}
	if len(i.ContractIDIn) > 0 {
		predicates = append(predicates, monitorevent.ContractIDIn(i.ContractIDIn...))
	}
	if len(i.ContractIDNotIn) > 0 {
		predicates = append(predicates, monitorevent.ContractIDNotIn(i.ContractIDNotIn...))
	}
	if i.ContractIDGT != nil {
		predicates = append(predicates, monitorevent.ContractIDGT(*i.ContractIDGT))
	}
	if i.ContractIDGTE != nil {
		predicates = append(predicates, monitorevent.ContractIDGTE(*i.ContractIDGTE))
	}
	if i.ContractIDLT != nil {
		predicates = append(predicates, monitorevent.ContractIDLT(*i.ContractIDLT))
	}
	if i.ContractIDLTE != nil {
		predicates = append(predicates, monitorevent.ContractIDLTE(*i.ContractIDLTE))
	}
	if i.EventName != nil {
		predicates = append(predicates, monitorevent.EventNameEQ(*i.EventName))
	}
	if i.EventNameNEQ != nil {
		predicates = append(predicates, monitorevent.EventNameNEQ(*i.EventNameNEQ))
	}
	if len(i.EventNameIn) > 0 {
		predicates = append(predicates, monitorevent.EventNameIn(i.EventNameIn...))
	}
	if len(i.EventNameNotIn) > 0 {
		predicates = append(predicates, monitorevent.EventNameNotIn(i.EventNameNotIn...))
	}
	if i.EventNameGT != nil {
		predicates = append(predicates, monitorevent.EventNameGT(*i.EventNameGT))
	}
	if i.EventNameGTE != nil {
		predicates = append(predicates, monitorevent.EventNameGTE(*i.EventNameGTE))
	}
	if i.EventNameLT != nil {
		predicates = append(predicates, monitorevent.EventNameLT(*i.EventNameLT))
	}
	if i.EventNameLTE != nil {
		predicates = append(predicates, monitorevent.EventNameLTE(*i.EventNameLTE))
	}
	if i.EventNameContains != nil {
		predicates = append(predicates, monitorevent.EventNameContains(*i.EventNameContains))
	}
	if i.EventNameHasPrefix != nil {
		predicates = append(predicates, monitorevent.EventNameHasPrefix(*i.EventNameHasPrefix))
	}
	if i.EventNameHasSuffix != nil {
		predicates = append(predicates, monitorevent.EventNameHasSuffix(*i.EventNameHasSuffix))
	}
	if i.EventNameEqualFold != nil {
		predicates = append(predicates, monitorevent.EventNameEqualFold(*i.EventNameEqualFold))
	}
	if i.EventNameContainsFold != nil {
		predicates = append(predicates, monitorevent.EventNameContainsFold(*i.EventNameContainsFold))
	}
	if i.MqRoutingKey != nil {
		predicates = append(predicates, monitorevent.MqRoutingKeyEQ(*i.MqRoutingKey))
	}
	if i.MqRoutingKeyNEQ != nil {
		predicates = append(predicates, monitorevent.MqRoutingKeyNEQ(*i.MqRoutingKeyNEQ))
	}
	if len(i.MqRoutingKeyIn) > 0 {
		predicates = append(predicates, monitorevent.MqRoutingKeyIn(i.MqRoutingKeyIn...))
	}
	if len(i.MqRoutingKeyNotIn) > 0 {
		predicates = append(predicates, monitorevent.MqRoutingKeyNotIn(i.MqRoutingKeyNotIn...))
	}
	if i.MqRoutingKeyGT != nil {
		predicates = append(predicates, monitorevent.MqRoutingKeyGT(*i.MqRoutingKeyGT))
	}
	if i.MqRoutingKeyGTE != nil {
		predicates = append(predicates, monitorevent.MqRoutingKeyGTE(*i.MqRoutingKeyGTE))
	}
	if i.MqRoutingKeyLT != nil {
		predicates = append(predicates, monitorevent.MqRoutingKeyLT(*i.MqRoutingKeyLT))
	}
	if i.MqRoutingKeyLTE != nil {
		predicates = append(predicates, monitorevent.MqRoutingKeyLTE(*i.MqRoutingKeyLTE))
	}
	if i.MqRoutingKeyContains != nil {
		predicates = append(predicates, monitorevent.MqRoutingKeyContains(*i.MqRoutingKeyContains))
	}
	if i.MqRoutingKeyHasPrefix != nil {
		predicates = append(predicates, monitorevent.MqRoutingKeyHasPrefix(*i.MqRoutingKeyHasPrefix))
	}
	if i.MqRoutingKeyHasSuffix != nil {
		predicates = append(predicates, monitorevent.MqRoutingKeyHasSuffix(*i.MqRoutingKeyHasSuffix))
	}
	if i.MqRoutingKeyEqualFold != nil {
		predicates = append(predicates, monitorevent.MqRoutingKeyEqualFold(*i.MqRoutingKeyEqualFold))
	}
	if i.MqRoutingKeyContainsFold != nil {
		predicates = append(predicates, monitorevent.MqRoutingKeyContainsFold(*i.MqRoutingKeyContainsFold))
	}
	if i.Status != nil {
		predicates = append(predicates, monitorevent.StatusEQ(*i.Status))
	}
	if i.StatusNEQ != nil {
		predicates = append(predicates, monitorevent.StatusNEQ(*i.StatusNEQ))
	}
	if len(i.StatusIn) > 0 {
		predicates = append(predicates, monitorevent.StatusIn(i.StatusIn...))
	}
	if len(i.StatusNotIn) > 0 {
		predicates = append(predicates, monitorevent.StatusNotIn(i.StatusNotIn...))
	}
	if i.StatusGT != nil {
		predicates = append(predicates, monitorevent.StatusGT(*i.StatusGT))
	}
	if i.StatusGTE != nil {
		predicates = append(predicates, monitorevent.StatusGTE(*i.StatusGTE))
	}
	if i.StatusLT != nil {
		predicates = append(predicates, monitorevent.StatusLT(*i.StatusLT))
	}
	if i.StatusLTE != nil {
		predicates = append(predicates, monitorevent.StatusLTE(*i.StatusLTE))
	}
	if i.LastBlock != nil {
		predicates = append(predicates, monitorevent.LastBlockEQ(*i.LastBlock))
	}
	if i.LastBlockNEQ != nil {
		predicates = append(predicates, monitorevent.LastBlockNEQ(*i.LastBlockNEQ))
	}
	if len(i.LastBlockIn) > 0 {
		predicates = append(predicates, monitorevent.LastBlockIn(i.LastBlockIn...))
	}
	if len(i.LastBlockNotIn) > 0 {
		predicates = append(predicates, monitorevent.LastBlockNotIn(i.LastBlockNotIn...))
	}
	if i.LastBlockGT != nil {
		predicates = append(predicates, monitorevent.LastBlockGT(*i.LastBlockGT))
	}
	if i.LastBlockGTE != nil {
		predicates = append(predicates, monitorevent.LastBlockGTE(*i.LastBlockGTE))
	}
	if i.LastBlockLT != nil {
		predicates = append(predicates, monitorevent.LastBlockLT(*i.LastBlockLT))
	}
	if i.LastBlockLTE != nil {
		predicates = append(predicates, monitorevent.LastBlockLTE(*i.LastBlockLTE))
	}

	switch len(predicates) {
	case 0:
		return nil, ErrEmptyMonitorEventWhereInput
	case 1:
		return predicates[0], nil
	default:
		return monitorevent.And(predicates...), nil
	}
}

// ParsedEventsLogWhereInput represents a where input for filtering ParsedEventsLog queries.
type ParsedEventsLogWhereInput struct {
	Predicates []predicate.ParsedEventsLog  `json:"-"`
	Not        *ParsedEventsLogWhereInput   `json:"not,omitempty"`
	Or         []*ParsedEventsLogWhereInput `json:"or,omitempty"`
	And        []*ParsedEventsLogWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *uuid.UUID  `json:"id,omitempty"`
	IDNEQ   *uuid.UUID  `json:"idNEQ,omitempty"`
	IDIn    []uuid.UUID `json:"idIn,omitempty"`
	IDNotIn []uuid.UUID `json:"idNotIn,omitempty"`
	IDGT    *uuid.UUID  `json:"idGT,omitempty"`
	IDGTE   *uuid.UUID  `json:"idGTE,omitempty"`
	IDLT    *uuid.UUID  `json:"idLT,omitempty"`
	IDLTE   *uuid.UUID  `json:"idLTE,omitempty"`

	// "uid" field predicates.
	UID             *string  `json:"uid,omitempty"`
	UIDNEQ          *string  `json:"uidNEQ,omitempty"`
	UIDIn           []string `json:"uidIn,omitempty"`
	UIDNotIn        []string `json:"uidNotIn,omitempty"`
	UIDGT           *string  `json:"uidGT,omitempty"`
	UIDGTE          *string  `json:"uidGTE,omitempty"`
	UIDLT           *string  `json:"uidLT,omitempty"`
	UIDLTE          *string  `json:"uidLTE,omitempty"`
	UIDContains     *string  `json:"uidContains,omitempty"`
	UIDHasPrefix    *string  `json:"uidHasPrefix,omitempty"`
	UIDHasSuffix    *string  `json:"uidHasSuffix,omitempty"`
	UIDEqualFold    *string  `json:"uidEqualFold,omitempty"`
	UIDContainsFold *string  `json:"uidContainsFold,omitempty"`

	// "event_id" field predicates.
	EventID      *uuid.UUID  `json:"eventID,omitempty"`
	EventIDNEQ   *uuid.UUID  `json:"eventIDNEQ,omitempty"`
	EventIDIn    []uuid.UUID `json:"eventIDIn,omitempty"`
	EventIDNotIn []uuid.UUID `json:"eventIDNotIn,omitempty"`
	EventIDGT    *uuid.UUID  `json:"eventIDGT,omitempty"`
	EventIDGTE   *uuid.UUID  `json:"eventIDGTE,omitempty"`
	EventIDLT    *uuid.UUID  `json:"eventIDLT,omitempty"`
	EventIDLTE   *uuid.UUID  `json:"eventIDLTE,omitempty"`

	// "block_number" field predicates.
	BlockNumber      *int64  `json:"blockNumber,omitempty"`
	BlockNumberNEQ   *int64  `json:"blockNumberNEQ,omitempty"`
	BlockNumberIn    []int64 `json:"blockNumberIn,omitempty"`
	BlockNumberNotIn []int64 `json:"blockNumberNotIn,omitempty"`
	BlockNumberGT    *int64  `json:"blockNumberGT,omitempty"`
	BlockNumberGTE   *int64  `json:"blockNumberGTE,omitempty"`
	BlockNumberLT    *int64  `json:"blockNumberLT,omitempty"`
	BlockNumberLTE   *int64  `json:"blockNumberLTE,omitempty"`

	// "tx_hash" field predicates.
	TxHash             *string  `json:"txHash,omitempty"`
	TxHashNEQ          *string  `json:"txHashNEQ,omitempty"`
	TxHashIn           []string `json:"txHashIn,omitempty"`
	TxHashNotIn        []string `json:"txHashNotIn,omitempty"`
	TxHashGT           *string  `json:"txHashGT,omitempty"`
	TxHashGTE          *string  `json:"txHashGTE,omitempty"`
	TxHashLT           *string  `json:"txHashLT,omitempty"`
	TxHashLTE          *string  `json:"txHashLTE,omitempty"`
	TxHashContains     *string  `json:"txHashContains,omitempty"`
	TxHashHasPrefix    *string  `json:"txHashHasPrefix,omitempty"`
	TxHashHasSuffix    *string  `json:"txHashHasSuffix,omitempty"`
	TxHashEqualFold    *string  `json:"txHashEqualFold,omitempty"`
	TxHashContainsFold *string  `json:"txHashContainsFold,omitempty"`

	// "log_index" field predicates.
	LogIndex      *int64  `json:"logIndex,omitempty"`
	LogIndexNEQ   *int64  `json:"logIndexNEQ,omitempty"`
	LogIndexIn    []int64 `json:"logIndexIn,omitempty"`
	LogIndexNotIn []int64 `json:"logIndexNotIn,omitempty"`
	LogIndexGT    *int64  `json:"logIndexGT,omitempty"`
	LogIndexGTE   *int64  `json:"logIndexGTE,omitempty"`
	LogIndexLT    *int64  `json:"logIndexLT,omitempty"`
	LogIndexLTE   *int64  `json:"logIndexLTE,omitempty"`

	// "created_at" field predicates.
	CreatedAt      *time.Time  `json:"createdAt,omitempty"`
	CreatedAtNEQ   *time.Time  `json:"createdAtNEQ,omitempty"`
	CreatedAtIn    []time.Time `json:"createdAtIn,omitempty"`
	CreatedAtNotIn []time.Time `json:"createdAtNotIn,omitempty"`
	CreatedAtGT    *time.Time  `json:"createdAtGT,omitempty"`
	CreatedAtGTE   *time.Time  `json:"createdAtGTE,omitempty"`
	CreatedAtLT    *time.Time  `json:"createdAtLT,omitempty"`
	CreatedAtLTE   *time.Time  `json:"createdAtLTE,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *ParsedEventsLogWhereInput) AddPredicates(predicates ...predicate.ParsedEventsLog) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the ParsedEventsLogWhereInput filter on the ParsedEventsLogQuery builder.
func (i *ParsedEventsLogWhereInput) Filter(q *ParsedEventsLogQuery) (*ParsedEventsLogQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyParsedEventsLogWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyParsedEventsLogWhereInput is returned in case the ParsedEventsLogWhereInput is empty.
var ErrEmptyParsedEventsLogWhereInput = errors.New("ent: empty predicate ParsedEventsLogWhereInput")

// P returns a predicate for filtering parsedeventslogs.
// An error is returned if the input is empty or invalid.
func (i *ParsedEventsLogWhereInput) P() (predicate.ParsedEventsLog, error) {
	var predicates []predicate.ParsedEventsLog
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, parsedeventslog.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.ParsedEventsLog, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, parsedeventslog.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.ParsedEventsLog, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, parsedeventslog.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, parsedeventslog.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, parsedeventslog.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, parsedeventslog.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, parsedeventslog.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, parsedeventslog.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, parsedeventslog.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, parsedeventslog.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, parsedeventslog.IDLTE(*i.IDLTE))
	}
	if i.UID != nil {
		predicates = append(predicates, parsedeventslog.UIDEQ(*i.UID))
	}
	if i.UIDNEQ != nil {
		predicates = append(predicates, parsedeventslog.UIDNEQ(*i.UIDNEQ))
	}
	if len(i.UIDIn) > 0 {
		predicates = append(predicates, parsedeventslog.UIDIn(i.UIDIn...))
	}
	if len(i.UIDNotIn) > 0 {
		predicates = append(predicates, parsedeventslog.UIDNotIn(i.UIDNotIn...))
	}
	if i.UIDGT != nil {
		predicates = append(predicates, parsedeventslog.UIDGT(*i.UIDGT))
	}
	if i.UIDGTE != nil {
		predicates = append(predicates, parsedeventslog.UIDGTE(*i.UIDGTE))
	}
	if i.UIDLT != nil {
		predicates = append(predicates, parsedeventslog.UIDLT(*i.UIDLT))
	}
	if i.UIDLTE != nil {
		predicates = append(predicates, parsedeventslog.UIDLTE(*i.UIDLTE))
	}
	if i.UIDContains != nil {
		predicates = append(predicates, parsedeventslog.UIDContains(*i.UIDContains))
	}
	if i.UIDHasPrefix != nil {
		predicates = append(predicates, parsedeventslog.UIDHasPrefix(*i.UIDHasPrefix))
	}
	if i.UIDHasSuffix != nil {
		predicates = append(predicates, parsedeventslog.UIDHasSuffix(*i.UIDHasSuffix))
	}
	if i.UIDEqualFold != nil {
		predicates = append(predicates, parsedeventslog.UIDEqualFold(*i.UIDEqualFold))
	}
	if i.UIDContainsFold != nil {
		predicates = append(predicates, parsedeventslog.UIDContainsFold(*i.UIDContainsFold))
	}
	if i.EventID != nil {
		predicates = append(predicates, parsedeventslog.EventIDEQ(*i.EventID))
	}
	if i.EventIDNEQ != nil {
		predicates = append(predicates, parsedeventslog.EventIDNEQ(*i.EventIDNEQ))
	}
	if len(i.EventIDIn) > 0 {
		predicates = append(predicates, parsedeventslog.EventIDIn(i.EventIDIn...))
	}
	if len(i.EventIDNotIn) > 0 {
		predicates = append(predicates, parsedeventslog.EventIDNotIn(i.EventIDNotIn...))
	}
	if i.EventIDGT != nil {
		predicates = append(predicates, parsedeventslog.EventIDGT(*i.EventIDGT))
	}
	if i.EventIDGTE != nil {
		predicates = append(predicates, parsedeventslog.EventIDGTE(*i.EventIDGTE))
	}
	if i.EventIDLT != nil {
		predicates = append(predicates, parsedeventslog.EventIDLT(*i.EventIDLT))
	}
	if i.EventIDLTE != nil {
		predicates = append(predicates, parsedeventslog.EventIDLTE(*i.EventIDLTE))
	}
	if i.BlockNumber != nil {
		predicates = append(predicates, parsedeventslog.BlockNumberEQ(*i.BlockNumber))
	}
	if i.BlockNumberNEQ != nil {
		predicates = append(predicates, parsedeventslog.BlockNumberNEQ(*i.BlockNumberNEQ))
	}
	if len(i.BlockNumberIn) > 0 {
		predicates = append(predicates, parsedeventslog.BlockNumberIn(i.BlockNumberIn...))
	}
	if len(i.BlockNumberNotIn) > 0 {
		predicates = append(predicates, parsedeventslog.BlockNumberNotIn(i.BlockNumberNotIn...))
	}
	if i.BlockNumberGT != nil {
		predicates = append(predicates, parsedeventslog.BlockNumberGT(*i.BlockNumberGT))
	}
	if i.BlockNumberGTE != nil {
		predicates = append(predicates, parsedeventslog.BlockNumberGTE(*i.BlockNumberGTE))
	}
	if i.BlockNumberLT != nil {
		predicates = append(predicates, parsedeventslog.BlockNumberLT(*i.BlockNumberLT))
	}
	if i.BlockNumberLTE != nil {
		predicates = append(predicates, parsedeventslog.BlockNumberLTE(*i.BlockNumberLTE))
	}
	if i.TxHash != nil {
		predicates = append(predicates, parsedeventslog.TxHashEQ(*i.TxHash))
	}
	if i.TxHashNEQ != nil {
		predicates = append(predicates, parsedeventslog.TxHashNEQ(*i.TxHashNEQ))
	}
	if len(i.TxHashIn) > 0 {
		predicates = append(predicates, parsedeventslog.TxHashIn(i.TxHashIn...))
	}
	if len(i.TxHashNotIn) > 0 {
		predicates = append(predicates, parsedeventslog.TxHashNotIn(i.TxHashNotIn...))
	}
	if i.TxHashGT != nil {
		predicates = append(predicates, parsedeventslog.TxHashGT(*i.TxHashGT))
	}
	if i.TxHashGTE != nil {
		predicates = append(predicates, parsedeventslog.TxHashGTE(*i.TxHashGTE))
	}
	if i.TxHashLT != nil {
		predicates = append(predicates, parsedeventslog.TxHashLT(*i.TxHashLT))
	}
	if i.TxHashLTE != nil {
		predicates = append(predicates, parsedeventslog.TxHashLTE(*i.TxHashLTE))
	}
	if i.TxHashContains != nil {
		predicates = append(predicates, parsedeventslog.TxHashContains(*i.TxHashContains))
	}
	if i.TxHashHasPrefix != nil {
		predicates = append(predicates, parsedeventslog.TxHashHasPrefix(*i.TxHashHasPrefix))
	}
	if i.TxHashHasSuffix != nil {
		predicates = append(predicates, parsedeventslog.TxHashHasSuffix(*i.TxHashHasSuffix))
	}
	if i.TxHashEqualFold != nil {
		predicates = append(predicates, parsedeventslog.TxHashEqualFold(*i.TxHashEqualFold))
	}
	if i.TxHashContainsFold != nil {
		predicates = append(predicates, parsedeventslog.TxHashContainsFold(*i.TxHashContainsFold))
	}
	if i.LogIndex != nil {
		predicates = append(predicates, parsedeventslog.LogIndexEQ(*i.LogIndex))
	}
	if i.LogIndexNEQ != nil {
		predicates = append(predicates, parsedeventslog.LogIndexNEQ(*i.LogIndexNEQ))
	}
	if len(i.LogIndexIn) > 0 {
		predicates = append(predicates, parsedeventslog.LogIndexIn(i.LogIndexIn...))
	}
	if len(i.LogIndexNotIn) > 0 {
		predicates = append(predicates, parsedeventslog.LogIndexNotIn(i.LogIndexNotIn...))
	}
	if i.LogIndexGT != nil {
		predicates = append(predicates, parsedeventslog.LogIndexGT(*i.LogIndexGT))
	}
	if i.LogIndexGTE != nil {
		predicates = append(predicates, parsedeventslog.LogIndexGTE(*i.LogIndexGTE))
	}
	if i.LogIndexLT != nil {
		predicates = append(predicates, parsedeventslog.LogIndexLT(*i.LogIndexLT))
	}
	if i.LogIndexLTE != nil {
		predicates = append(predicates, parsedeventslog.LogIndexLTE(*i.LogIndexLTE))
	}
	if i.CreatedAt != nil {
		predicates = append(predicates, parsedeventslog.CreatedAtEQ(*i.CreatedAt))
	}
	if i.CreatedAtNEQ != nil {
		predicates = append(predicates, parsedeventslog.CreatedAtNEQ(*i.CreatedAtNEQ))
	}
	if len(i.CreatedAtIn) > 0 {
		predicates = append(predicates, parsedeventslog.CreatedAtIn(i.CreatedAtIn...))
	}
	if len(i.CreatedAtNotIn) > 0 {
		predicates = append(predicates, parsedeventslog.CreatedAtNotIn(i.CreatedAtNotIn...))
	}
	if i.CreatedAtGT != nil {
		predicates = append(predicates, parsedeventslog.CreatedAtGT(*i.CreatedAtGT))
	}
	if i.CreatedAtGTE != nil {
		predicates = append(predicates, parsedeventslog.CreatedAtGTE(*i.CreatedAtGTE))
	}
	if i.CreatedAtLT != nil {
		predicates = append(predicates, parsedeventslog.CreatedAtLT(*i.CreatedAtLT))
	}
	if i.CreatedAtLTE != nil {
		predicates = append(predicates, parsedeventslog.CreatedAtLTE(*i.CreatedAtLTE))
	}

	switch len(predicates) {
	case 0:
		return nil, ErrEmptyParsedEventsLogWhereInput
	case 1:
		return predicates[0], nil
	default:
		return parsedeventslog.And(predicates...), nil
	}
}
