// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"nexus-chain/ent/monitorcontract"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// MonitorContract is the model entity for the MonitorContract schema.
type MonitorContract struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key ID
	ID uuid.UUID `json:"id,omitempty"`
	// Chain ID (e.g., 1 for mainnet, 11155111 for Sepolia)
	ChainID int `json:"chain_id,omitempty"`
	// Contract address
	Address string `json:"address,omitempty"`
	// Contract alias for easy identification
	Name string `json:"name,omitempty"`
	// Contract ABI definition
	Abi json.RawMessage `json:"abi,omitempty"`
	// Contract deployment block
	DeployedBlock int64 `json:"deployed_block,omitempty"`
	// Whether to enable monitoring (0: stop, 1: run)
	Status       int8 `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MonitorContract) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case monitorcontract.FieldAbi:
			values[i] = new([]byte)
		case monitorcontract.FieldChainID, monitorcontract.FieldDeployedBlock, monitorcontract.FieldStatus:
			values[i] = new(sql.NullInt64)
		case monitorcontract.FieldAddress, monitorcontract.FieldName:
			values[i] = new(sql.NullString)
		case monitorcontract.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MonitorContract fields.
func (_m *MonitorContract) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case monitorcontract.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case monitorcontract.FieldChainID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chain_id", values[i])
			} else if value.Valid {
				_m.ChainID = int(value.Int64)
			}
		case monitorcontract.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case monitorcontract.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case monitorcontract.FieldAbi:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field abi", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Abi); err != nil {
					return fmt.Errorf("unmarshal field abi: %w", err)
				}
			}
		case monitorcontract.FieldDeployedBlock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deployed_block", values[i])
			} else if value.Valid {
				_m.DeployedBlock = value.Int64
			}
		case monitorcontract.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int8(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MonitorContract.
// This includes values selected through modifiers, order, etc.
func (_m *MonitorContract) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MonitorContract.
// Note that you need to call MonitorContract.Unwrap() before calling this method if this MonitorContract
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MonitorContract) Update() *MonitorContractUpdateOne {
	return NewMonitorContractClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MonitorContract entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MonitorContract) Unwrap() *MonitorContract {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MonitorContract is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MonitorContract) String() string {
	var builder strings.Builder
	builder.WriteString("MonitorContract(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("chain_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChainID))
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("abi=")
	builder.WriteString(fmt.Sprintf("%v", _m.Abi))
	builder.WriteString(", ")
	builder.WriteString("deployed_block=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeployedBlock))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// MonitorContracts is a parsable slice of MonitorContract.
type MonitorContracts []*MonitorContract
