// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"nexus-chain/ent/monitorevent"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// MonitorEvent is the model entity for the MonitorEvent schema.
type MonitorEvent struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key ID
	ID uuid.UUID `json:"id,omitempty"`
	// Foreign key to monitor_contracts.id
	ContractID uuid.UUID `json:"contract_id,omitempty"`
	// Event name
	EventName string `json:"event_name,omitempty"`
	// MQ routing key for this event
	MqRoutingKey string `json:"mq_routing_key,omitempty"`
	// Whether to enable monitoring (0: stop, 1: run)
	Status int8 `json:"status,omitempty"`
	// Last processed block number
	LastBlock    int64 `json:"last_block,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MonitorEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case monitorevent.FieldStatus, monitorevent.FieldLastBlock:
			values[i] = new(sql.NullInt64)
		case monitorevent.FieldEventName, monitorevent.FieldMqRoutingKey:
			values[i] = new(sql.NullString)
		case monitorevent.FieldID, monitorevent.FieldContractID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MonitorEvent fields.
func (_m *MonitorEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case monitorevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case monitorevent.FieldContractID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field contract_id", values[i])
			} else if value != nil {
				_m.ContractID = *value
			}
		case monitorevent.FieldEventName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_name", values[i])
			} else if value.Valid {
				_m.EventName = value.String
			}
		case monitorevent.FieldMqRoutingKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mq_routing_key", values[i])
			} else if value.Valid {
				_m.MqRoutingKey = value.String
			}
		case monitorevent.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int8(value.Int64)
			}
		case monitorevent.FieldLastBlock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_block", values[i])
			} else if value.Valid {
				_m.LastBlock = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MonitorEvent.
// This includes values selected through modifiers, order, etc.
func (_m *MonitorEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MonitorEvent.
// Note that you need to call MonitorEvent.Unwrap() before calling this method if this MonitorEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MonitorEvent) Update() *MonitorEventUpdateOne {
	return NewMonitorEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MonitorEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MonitorEvent) Unwrap() *MonitorEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MonitorEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MonitorEvent) String() string {
	var builder strings.Builder
	builder.WriteString("MonitorEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("contract_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContractID))
	builder.WriteString(", ")
	builder.WriteString("event_name=")
	builder.WriteString(_m.EventName)
	builder.WriteString(", ")
	builder.WriteString("mq_routing_key=")
	builder.WriteString(_m.MqRoutingKey)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("last_block=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastBlock))
	builder.WriteByte(')')
	return builder.String()
}

// MonitorEvents is a parsable slice of MonitorEvent.
type MonitorEvents []*MonitorEvent
