// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"nexus-chain/ent/monitorcontract"
	"nexus-chain/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MonitorContractDelete is the builder for deleting a MonitorContract entity.
type MonitorContractDelete struct {
	config
	hooks    []Hook
	mutation *MonitorContractMutation
}

// Where appends a list predicates to the MonitorContractDelete builder.
func (_d *MonitorContractDelete) Where(ps ...predicate.MonitorContract) *MonitorContractDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MonitorContractDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MonitorContractDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MonitorContractDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(monitorcontract.Table, sqlgraph.NewFieldSpec(monitorcontract.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MonitorContractDeleteOne is the builder for deleting a single MonitorContract entity.
type MonitorContractDeleteOne struct {
	_d *MonitorContractDelete
}

// Where appends a list predicates to the MonitorContractDelete builder.
func (_d *MonitorContractDeleteOne) Where(ps ...predicate.MonitorContract) *MonitorContractDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MonitorContractDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{monitorcontract.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MonitorContractDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
