// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nexus-chain/ent/monitorevent"
	"nexus-chain/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MonitorEventUpdate is the builder for updating MonitorEvent entities.
type MonitorEventUpdate struct {
	config
	hooks     []Hook
	mutation  *MonitorEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MonitorEventUpdate builder.
func (_u *MonitorEventUpdate) Where(ps ...predicate.MonitorEvent) *MonitorEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContractID sets the "contract_id" field.
func (_u *MonitorEventUpdate) SetContractID(v uuid.UUID) *MonitorEventUpdate {
	_u.mutation.SetContractID(v)
	return _u
}

// SetNillableContractID sets the "contract_id" field if the given value is not nil.
func (_u *MonitorEventUpdate) SetNillableContractID(v *uuid.UUID) *MonitorEventUpdate {
	if v != nil {
		_u.SetContractID(*v)
	}
	return _u
}

// SetEventName sets the "event_name" field.
func (_u *MonitorEventUpdate) SetEventName(v string) *MonitorEventUpdate {
	_u.mutation.SetEventName(v)
	return _u
}

// SetNillableEventName sets the "event_name" field if the given value is not nil.
func (_u *MonitorEventUpdate) SetNillableEventName(v *string) *MonitorEventUpdate {
	if v != nil {
		_u.SetEventName(*v)
	}
	return _u
}

// SetMqRoutingKey sets the "mq_routing_key" field.
func (_u *MonitorEventUpdate) SetMqRoutingKey(v string) *MonitorEventUpdate {
	_u.mutation.SetMqRoutingKey(v)
	return _u
}

// SetNillableMqRoutingKey sets the "mq_routing_key" field if the given value is not nil.
func (_u *MonitorEventUpdate) SetNillableMqRoutingKey(v *string) *MonitorEventUpdate {
	if v != nil {
		_u.SetMqRoutingKey(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MonitorEventUpdate) SetStatus(v int8) *MonitorEventUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MonitorEventUpdate) SetNillableStatus(v *int8) *MonitorEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *MonitorEventUpdate) AddStatus(v int8) *MonitorEventUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetLastBlock sets the "last_block" field.
func (_u *MonitorEventUpdate) SetLastBlock(v int64) *MonitorEventUpdate {
	_u.mutation.ResetLastBlock()
	_u.mutation.SetLastBlock(v)
	return _u
}

// SetNillableLastBlock sets the "last_block" field if the given value is not nil.
func (_u *MonitorEventUpdate) SetNillableLastBlock(v *int64) *MonitorEventUpdate {
	if v != nil {
		_u.SetLastBlock(*v)
	}
	return _u
}

// AddLastBlock adds value to the "last_block" field.
func (_u *MonitorEventUpdate) AddLastBlock(v int64) *MonitorEventUpdate {
	_u.mutation.AddLastBlock(v)
	return _u
}

// Mutation returns the MonitorEventMutation object of the builder.
func (_u *MonitorEventUpdate) Mutation() *MonitorEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MonitorEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MonitorEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MonitorEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MonitorEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MonitorEventUpdate) check() error {
	if v, ok := _u.mutation.EventName(); ok {
		if err := monitorevent.EventNameValidator(v); err != nil {
			return &ValidationError{Name: "event_name", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.event_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MqRoutingKey(); ok {
		if err := monitorevent.MqRoutingKeyValidator(v); err != nil {
			return &ValidationError{Name: "mq_routing_key", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.mq_routing_key": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MonitorEventUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MonitorEventUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MonitorEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitorevent.Table, monitorevent.Columns, sqlgraph.NewFieldSpec(monitorevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ContractID(); ok {
		_spec.SetField(monitorevent.FieldContractID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EventName(); ok {
		_spec.SetField(monitorevent.FieldEventName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MqRoutingKey(); ok {
		_spec.SetField(monitorevent.FieldMqRoutingKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(monitorevent.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(monitorevent.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.LastBlock(); ok {
		_spec.SetField(monitorevent.FieldLastBlock, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastBlock(); ok {
		_spec.AddField(monitorevent.FieldLastBlock, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitorevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MonitorEventUpdateOne is the builder for updating a single MonitorEvent entity.
type MonitorEventUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MonitorEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetContractID sets the "contract_id" field.
func (_u *MonitorEventUpdateOne) SetContractID(v uuid.UUID) *MonitorEventUpdateOne {
	_u.mutation.SetContractID(v)
	return _u
}

// SetNillableContractID sets the "contract_id" field if the given value is not nil.
func (_u *MonitorEventUpdateOne) SetNillableContractID(v *uuid.UUID) *MonitorEventUpdateOne {
	if v != nil {
		_u.SetContractID(*v)
	}
	return _u
}

// SetEventName sets the "event_name" field.
func (_u *MonitorEventUpdateOne) SetEventName(v string) *MonitorEventUpdateOne {
	_u.mutation.SetEventName(v)
	return _u
}

// SetNillableEventName sets the "event_name" field if the given value is not nil.
func (_u *MonitorEventUpdateOne) SetNillableEventName(v *string) *MonitorEventUpdateOne {
	if v != nil {
		_u.SetEventName(*v)
	}
	return _u
}

// SetMqRoutingKey sets the "mq_routing_key" field.
func (_u *MonitorEventUpdateOne) SetMqRoutingKey(v string) *MonitorEventUpdateOne {
	_u.mutation.SetMqRoutingKey(v)
	return _u
}

// SetNillableMqRoutingKey sets the "mq_routing_key" field if the given value is not nil.
func (_u *MonitorEventUpdateOne) SetNillableMqRoutingKey(v *string) *MonitorEventUpdateOne {
	if v != nil {
		_u.SetMqRoutingKey(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MonitorEventUpdateOne) SetStatus(v int8) *MonitorEventUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MonitorEventUpdateOne) SetNillableStatus(v *int8) *MonitorEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *MonitorEventUpdateOne) AddStatus(v int8) *MonitorEventUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetLastBlock sets the "last_block" field.
func (_u *MonitorEventUpdateOne) SetLastBlock(v int64) *MonitorEventUpdateOne {
	_u.mutation.ResetLastBlock()
	_u.mutation.SetLastBlock(v)
	return _u
}

// SetNillableLastBlock sets the "last_block" field if the given value is not nil.
func (_u *MonitorEventUpdateOne) SetNillableLastBlock(v *int64) *MonitorEventUpdateOne {
	if v != nil {
		_u.SetLastBlock(*v)
	}
	return _u
}

// AddLastBlock adds value to the "last_block" field.
func (_u *MonitorEventUpdateOne) AddLastBlock(v int64) *MonitorEventUpdateOne {
	_u.mutation.AddLastBlock(v)
	return _u
}

// Mutation returns the MonitorEventMutation object of the builder.
func (_u *MonitorEventUpdateOne) Mutation() *MonitorEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the MonitorEventUpdate builder.
func (_u *MonitorEventUpdateOne) Where(ps ...predicate.MonitorEvent) *MonitorEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MonitorEventUpdateOne) Select(field string, fields ...string) *MonitorEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MonitorEvent entity.
func (_u *MonitorEventUpdateOne) Save(ctx context.Context) (*MonitorEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MonitorEventUpdateOne) SaveX(ctx context.Context) *MonitorEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MonitorEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MonitorEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MonitorEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventName(); ok {
		if err := monitorevent.EventNameValidator(v); err != nil {
			return &ValidationError{Name: "event_name", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.event_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MqRoutingKey(); ok {
		if err := monitorevent.MqRoutingKeyValidator(v); err != nil {
			return &ValidationError{Name: "mq_routing_key", err: fmt.Errorf(`ent: validator failed for field "MonitorEvent.mq_routing_key": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MonitorEventUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MonitorEventUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MonitorEventUpdateOne) sqlSave(ctx context.Context) (_node *MonitorEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitorevent.Table, monitorevent.Columns, sqlgraph.NewFieldSpec(monitorevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MonitorEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, monitorevent.FieldID)
		for _, f := range fields {
			if !monitorevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != monitorevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ContractID(); ok {
		_spec.SetField(monitorevent.FieldContractID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EventName(); ok {
		_spec.SetField(monitorevent.FieldEventName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MqRoutingKey(); ok {
		_spec.SetField(monitorevent.FieldMqRoutingKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(monitorevent.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(monitorevent.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.LastBlock(); ok {
		_spec.SetField(monitorevent.FieldLastBlock, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastBlock(); ok {
		_spec.AddField(monitorevent.FieldLastBlock, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &MonitorEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitorevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
