// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"nexus-chain/ent/monitorcontract"
	"nexus-chain/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// MonitorContractUpdate is the builder for updating MonitorContract entities.
type MonitorContractUpdate struct {
	config
	hooks     []Hook
	mutation  *MonitorContractMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MonitorContractUpdate builder.
func (_u *MonitorContractUpdate) Where(ps ...predicate.MonitorContract) *MonitorContractUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChainID sets the "chain_id" field.
func (_u *MonitorContractUpdate) SetChainID(v int) *MonitorContractUpdate {
	_u.mutation.ResetChainID()
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *MonitorContractUpdate) SetNillableChainID(v *int) *MonitorContractUpdate {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// AddChainID adds value to the "chain_id" field.
func (_u *MonitorContractUpdate) AddChainID(v int) *MonitorContractUpdate {
	_u.mutation.AddChainID(v)
	return _u
}

// SetAddress sets the "address" field.
func (_u *MonitorContractUpdate) SetAddress(v string) *MonitorContractUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *MonitorContractUpdate) SetNillableAddress(v *string) *MonitorContractUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *MonitorContractUpdate) SetName(v string) *MonitorContractUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MonitorContractUpdate) SetNillableName(v *string) *MonitorContractUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAbi sets the "abi" field.
func (_u *MonitorContractUpdate) SetAbi(v json.RawMessage) *MonitorContractUpdate {
	_u.mutation.SetAbi(v)
	return _u
}

// AppendAbi appends value to the "abi" field.
func (_u *MonitorContractUpdate) AppendAbi(v json.RawMessage) *MonitorContractUpdate {
	_u.mutation.AppendAbi(v)
	return _u
}

// SetRPCURL sets the "rpc_url" field.
func (_u *MonitorContractUpdate) SetRPCURL(v string) *MonitorContractUpdate {
	_u.mutation.SetRPCURL(v)
	return _u
}

// SetNillableRPCURL sets the "rpc_url" field if the given value is not nil.
func (_u *MonitorContractUpdate) SetNillableRPCURL(v *string) *MonitorContractUpdate {
	if v != nil {
		_u.SetRPCURL(*v)
	}
	return _u
}

// SetWsURL sets the "ws_url" field.
func (_u *MonitorContractUpdate) SetWsURL(v string) *MonitorContractUpdate {
	_u.mutation.SetWsURL(v)
	return _u
}

// SetNillableWsURL sets the "ws_url" field if the given value is not nil.
func (_u *MonitorContractUpdate) SetNillableWsURL(v *string) *MonitorContractUpdate {
	if v != nil {
		_u.SetWsURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MonitorContractUpdate) SetStatus(v int8) *MonitorContractUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MonitorContractUpdate) SetNillableStatus(v *int8) *MonitorContractUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *MonitorContractUpdate) AddStatus(v int8) *MonitorContractUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// Mutation returns the MonitorContractMutation object of the builder.
func (_u *MonitorContractUpdate) Mutation() *MonitorContractMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MonitorContractUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MonitorContractUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MonitorContractUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MonitorContractUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MonitorContractUpdate) check() error {
	if v, ok := _u.mutation.Address(); ok {
		if err := monitorcontract.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "MonitorContract.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := monitorcontract.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MonitorContract.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RPCURL(); ok {
		if err := monitorcontract.RPCURLValidator(v); err != nil {
			return &ValidationError{Name: "rpc_url", err: fmt.Errorf(`ent: validator failed for field "MonitorContract.rpc_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WsURL(); ok {
		if err := monitorcontract.WsURLValidator(v); err != nil {
			return &ValidationError{Name: "ws_url", err: fmt.Errorf(`ent: validator failed for field "MonitorContract.ws_url": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MonitorContractUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MonitorContractUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MonitorContractUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitorcontract.Table, monitorcontract.Columns, sqlgraph.NewFieldSpec(monitorcontract.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChainID(); ok {
		_spec.SetField(monitorcontract.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChainID(); ok {
		_spec.AddField(monitorcontract.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(monitorcontract.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(monitorcontract.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Abi(); ok {
		_spec.SetField(monitorcontract.FieldAbi, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAbi(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, monitorcontract.FieldAbi, value)
		})
	}
	if value, ok := _u.mutation.RPCURL(); ok {
		_spec.SetField(monitorcontract.FieldRPCURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.WsURL(); ok {
		_spec.SetField(monitorcontract.FieldWsURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(monitorcontract.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(monitorcontract.FieldStatus, field.TypeInt8, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitorcontract.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MonitorContractUpdateOne is the builder for updating a single MonitorContract entity.
type MonitorContractUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MonitorContractMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetChainID sets the "chain_id" field.
func (_u *MonitorContractUpdateOne) SetChainID(v int) *MonitorContractUpdateOne {
	_u.mutation.ResetChainID()
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *MonitorContractUpdateOne) SetNillableChainID(v *int) *MonitorContractUpdateOne {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// AddChainID adds value to the "chain_id" field.
func (_u *MonitorContractUpdateOne) AddChainID(v int) *MonitorContractUpdateOne {
	_u.mutation.AddChainID(v)
	return _u
}

// SetAddress sets the "address" field.
func (_u *MonitorContractUpdateOne) SetAddress(v string) *MonitorContractUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *MonitorContractUpdateOne) SetNillableAddress(v *string) *MonitorContractUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *MonitorContractUpdateOne) SetName(v string) *MonitorContractUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MonitorContractUpdateOne) SetNillableName(v *string) *MonitorContractUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAbi sets the "abi" field.
func (_u *MonitorContractUpdateOne) SetAbi(v json.RawMessage) *MonitorContractUpdateOne {
	_u.mutation.SetAbi(v)
	return _u
}

// AppendAbi appends value to the "abi" field.
func (_u *MonitorContractUpdateOne) AppendAbi(v json.RawMessage) *MonitorContractUpdateOne {
	_u.mutation.AppendAbi(v)
	return _u
}

// SetRPCURL sets the "rpc_url" field.
func (_u *MonitorContractUpdateOne) SetRPCURL(v string) *MonitorContractUpdateOne {
	_u.mutation.SetRPCURL(v)
	return _u
}

// SetNillableRPCURL sets the "rpc_url" field if the given value is not nil.
func (_u *MonitorContractUpdateOne) SetNillableRPCURL(v *string) *MonitorContractUpdateOne {
	if v != nil {
		_u.SetRPCURL(*v)
	}
	return _u
}

// SetWsURL sets the "ws_url" field.
func (_u *MonitorContractUpdateOne) SetWsURL(v string) *MonitorContractUpdateOne {
	_u.mutation.SetWsURL(v)
	return _u
}

// SetNillableWsURL sets the "ws_url" field if the given value is not nil.
func (_u *MonitorContractUpdateOne) SetNillableWsURL(v *string) *MonitorContractUpdateOne {
	if v != nil {
		_u.SetWsURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MonitorContractUpdateOne) SetStatus(v int8) *MonitorContractUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MonitorContractUpdateOne) SetNillableStatus(v *int8) *MonitorContractUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *MonitorContractUpdateOne) AddStatus(v int8) *MonitorContractUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// Mutation returns the MonitorContractMutation object of the builder.
func (_u *MonitorContractUpdateOne) Mutation() *MonitorContractMutation {
	return _u.mutation
}

// Where appends a list predicates to the MonitorContractUpdate builder.
func (_u *MonitorContractUpdateOne) Where(ps ...predicate.MonitorContract) *MonitorContractUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MonitorContractUpdateOne) Select(field string, fields ...string) *MonitorContractUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MonitorContract entity.
func (_u *MonitorContractUpdateOne) Save(ctx context.Context) (*MonitorContract, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MonitorContractUpdateOne) SaveX(ctx context.Context) *MonitorContract {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MonitorContractUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MonitorContractUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MonitorContractUpdateOne) check() error {
	if v, ok := _u.mutation.Address(); ok {
		if err := monitorcontract.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "MonitorContract.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := monitorcontract.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MonitorContract.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RPCURL(); ok {
		if err := monitorcontract.RPCURLValidator(v); err != nil {
			return &ValidationError{Name: "rpc_url", err: fmt.Errorf(`ent: validator failed for field "MonitorContract.rpc_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WsURL(); ok {
		if err := monitorcontract.WsURLValidator(v); err != nil {
			return &ValidationError{Name: "ws_url", err: fmt.Errorf(`ent: validator failed for field "MonitorContract.ws_url": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MonitorContractUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MonitorContractUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MonitorContractUpdateOne) sqlSave(ctx context.Context) (_node *MonitorContract, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitorcontract.Table, monitorcontract.Columns, sqlgraph.NewFieldSpec(monitorcontract.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MonitorContract.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, monitorcontract.FieldID)
		for _, f := range fields {
			if !monitorcontract.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != monitorcontract.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChainID(); ok {
		_spec.SetField(monitorcontract.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChainID(); ok {
		_spec.AddField(monitorcontract.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(monitorcontract.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(monitorcontract.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Abi(); ok {
		_spec.SetField(monitorcontract.FieldAbi, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAbi(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, monitorcontract.FieldAbi, value)
		})
	}
	if value, ok := _u.mutation.RPCURL(); ok {
		_spec.SetField(monitorcontract.FieldRPCURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.WsURL(); ok {
		_spec.SetField(monitorcontract.FieldWsURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(monitorcontract.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(monitorcontract.FieldStatus, field.TypeInt8, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &MonitorContract{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitorcontract.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
