// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"nexus-chain/ent/monitorevent"
	"nexus-chain/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MonitorEventDelete is the builder for deleting a MonitorEvent entity.
type MonitorEventDelete struct {
	config
	hooks    []Hook
	mutation *MonitorEventMutation
}

// Where appends a list predicates to the MonitorEventDelete builder.
func (_d *MonitorEventDelete) Where(ps ...predicate.MonitorEvent) *MonitorEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MonitorEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MonitorEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MonitorEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(monitorevent.Table, sqlgraph.NewFieldSpec(monitorevent.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MonitorEventDeleteOne is the builder for deleting a single MonitorEvent entity.
type MonitorEventDeleteOne struct {
	_d *MonitorEventDelete
}

// Where appends a list predicates to the MonitorEventDelete builder.
func (_d *MonitorEventDeleteOne) Where(ps ...predicate.MonitorEvent) *MonitorEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MonitorEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{monitorevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MonitorEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
