// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"nexus-chain/ent/monitorcontract"
	"nexus-chain/ent/monitorevent"
	"nexus-chain/ent/parsedeventslog"
	"nexus-chain/ent/predicate"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeMonitorContract = "MonitorContract"
	TypeMonitorEvent    = "MonitorEvent"
	TypeParsedEventsLog = "ParsedEventsLog"
)

// MonitorContractMutation represents an operation that mutates the MonitorContract nodes in the graph.
type MonitorContractMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	chain_id      *int
	addchain_id   *int
	address       *string
	name          *string
	abi           *json.RawMessage
	appendabi     json.RawMessage
	status        *int8
	addstatus     *int8
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*MonitorContract, error)
	predicates    []predicate.MonitorContract
}

var _ ent.Mutation = (*MonitorContractMutation)(nil)

// monitorcontractOption allows management of the mutation configuration using functional options.
type monitorcontractOption func(*MonitorContractMutation)

// newMonitorContractMutation creates new mutation for the MonitorContract entity.
func newMonitorContractMutation(c config, op Op, opts ...monitorcontractOption) *MonitorContractMutation {
	m := &MonitorContractMutation{
		config:        c,
		op:            op,
		typ:           TypeMonitorContract,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMonitorContractID sets the ID field of the mutation.
func withMonitorContractID(id uuid.UUID) monitorcontractOption {
	return func(m *MonitorContractMutation) {
		var (
			err   error
			once  sync.Once
			value *MonitorContract
		)
		m.oldValue = func(ctx context.Context) (*MonitorContract, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().MonitorContract.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMonitorContract sets the old MonitorContract of the mutation.
func withMonitorContract(node *MonitorContract) monitorcontractOption {
	return func(m *MonitorContractMutation) {
		m.oldValue = func(context.Context) (*MonitorContract, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MonitorContractMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MonitorContractMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of MonitorContract entities.
func (m *MonitorContractMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MonitorContractMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MonitorContractMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().MonitorContract.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetChainID sets the "chain_id" field.
func (m *MonitorContractMutation) SetChainID(i int) {
	m.chain_id = &i
	m.addchain_id = nil
}

// ChainID returns the value of the "chain_id" field in the mutation.
func (m *MonitorContractMutation) ChainID() (r int, exists bool) {
	v := m.chain_id
	if v == nil {
		return
	}
	return *v, true
}

// OldChainID returns the old "chain_id" field's value of the MonitorContract entity.
// If the MonitorContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MonitorContractMutation) OldChainID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldChainID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldChainID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldChainID: %w", err)
	}
	return oldValue.ChainID, nil
}

// AddChainID adds i to the "chain_id" field.
func (m *MonitorContractMutation) AddChainID(i int) {
	if m.addchain_id != nil {
		*m.addchain_id += i
	} else {
		m.addchain_id = &i
	}
}

// AddedChainID returns the value that was added to the "chain_id" field in this mutation.
func (m *MonitorContractMutation) AddedChainID() (r int, exists bool) {
	v := m.addchain_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetChainID resets all changes to the "chain_id" field.
func (m *MonitorContractMutation) ResetChainID() {
	m.chain_id = nil
	m.addchain_id = nil
}

// SetAddress sets the "address" field.
func (m *MonitorContractMutation) SetAddress(s string) {
	m.address = &s
}

// Address returns the value of the "address" field in the mutation.
func (m *MonitorContractMutation) Address() (r string, exists bool) {
	v := m.address
	if v == nil {
		return
	}
	return *v, true
}

// OldAddress returns the old "address" field's value of the MonitorContract entity.
// If the MonitorContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MonitorContractMutation) OldAddress(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAddress: %w", err)
	}
	return oldValue.Address, nil
}

// ResetAddress resets all changes to the "address" field.
func (m *MonitorContractMutation) ResetAddress() {
	m.address = nil
}

// SetName sets the "name" field.
func (m *MonitorContractMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *MonitorContractMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the MonitorContract entity.
// If the MonitorContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MonitorContractMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *MonitorContractMutation) ResetName() {
	m.name = nil
}

// SetAbi sets the "abi" field.
func (m *MonitorContractMutation) SetAbi(jm json.RawMessage) {
	m.abi = &jm
	m.appendabi = nil
}

// Abi returns the value of the "abi" field in the mutation.
func (m *MonitorContractMutation) Abi() (r json.RawMessage, exists bool) {
	v := m.abi
	if v == nil {
		return
	}
	return *v, true
}

// OldAbi returns the old "abi" field's value of the MonitorContract entity.
// If the MonitorContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MonitorContractMutation) OldAbi(ctx context.Context) (v json.RawMessage, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAbi is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAbi requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAbi: %w", err)
	}
	return oldValue.Abi, nil
}

// AppendAbi adds jm to the "abi" field.
func (m *MonitorContractMutation) AppendAbi(jm json.RawMessage) {
	m.appendabi = append(m.appendabi, jm...)
}

// AppendedAbi returns the list of values that were appended to the "abi" field in this mutation.
func (m *MonitorContractMutation) AppendedAbi() (json.RawMessage, bool) {
	if len(m.appendabi) == 0 {
		return nil, false
	}
	return m.appendabi, true
}

// ResetAbi resets all changes to the "abi" field.
func (m *MonitorContractMutation) ResetAbi() {
	m.abi = nil
	m.appendabi = nil
}

// SetStatus sets the "status" field.
func (m *MonitorContractMutation) SetStatus(i int8) {
	m.status = &i
	m.addstatus = nil
}

// Status returns the value of the "status" field in the mutation.
func (m *MonitorContractMutation) Status() (r int8, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the MonitorContract entity.
// If the MonitorContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MonitorContractMutation) OldStatus(ctx context.Context) (v int8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// AddStatus adds i to the "status" field.
func (m *MonitorContractMutation) AddStatus(i int8) {
	if m.addstatus != nil {
		*m.addstatus += i
	} else {
		m.addstatus = &i
	}
}

// AddedStatus returns the value that was added to the "status" field in this mutation.
func (m *MonitorContractMutation) AddedStatus() (r int8, exists bool) {
	v := m.addstatus
	if v == nil {
		return
	}
	return *v, true
}

// ResetStatus resets all changes to the "status" field.
func (m *MonitorContractMutation) ResetStatus() {
	m.status = nil
	m.addstatus = nil
}

// Where appends a list predicates to the MonitorContractMutation builder.
func (m *MonitorContractMutation) Where(ps ...predicate.MonitorContract) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MonitorContractMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MonitorContractMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.MonitorContract, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MonitorContractMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MonitorContractMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (MonitorContract).
func (m *MonitorContractMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MonitorContractMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.chain_id != nil {
		fields = append(fields, monitorcontract.FieldChainID)
	}
	if m.address != nil {
		fields = append(fields, monitorcontract.FieldAddress)
	}
	if m.name != nil {
		fields = append(fields, monitorcontract.FieldName)
	}
	if m.abi != nil {
		fields = append(fields, monitorcontract.FieldAbi)
	}
	if m.status != nil {
		fields = append(fields, monitorcontract.FieldStatus)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MonitorContractMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case monitorcontract.FieldChainID:
		return m.ChainID()
	case monitorcontract.FieldAddress:
		return m.Address()
	case monitorcontract.FieldName:
		return m.Name()
	case monitorcontract.FieldAbi:
		return m.Abi()
	case monitorcontract.FieldStatus:
		return m.Status()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MonitorContractMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case monitorcontract.FieldChainID:
		return m.OldChainID(ctx)
	case monitorcontract.FieldAddress:
		return m.OldAddress(ctx)
	case monitorcontract.FieldName:
		return m.OldName(ctx)
	case monitorcontract.FieldAbi:
		return m.OldAbi(ctx)
	case monitorcontract.FieldStatus:
		return m.OldStatus(ctx)
	}
	return nil, fmt.Errorf("unknown MonitorContract field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MonitorContractMutation) SetField(name string, value ent.Value) error {
	switch name {
	case monitorcontract.FieldChainID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetChainID(v)
		return nil
	case monitorcontract.FieldAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAddress(v)
		return nil
	case monitorcontract.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case monitorcontract.FieldAbi:
		v, ok := value.(json.RawMessage)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAbi(v)
		return nil
	case monitorcontract.FieldStatus:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	}
	return fmt.Errorf("unknown MonitorContract field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MonitorContractMutation) AddedFields() []string {
	var fields []string
	if m.addchain_id != nil {
		fields = append(fields, monitorcontract.FieldChainID)
	}
	if m.addstatus != nil {
		fields = append(fields, monitorcontract.FieldStatus)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MonitorContractMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case monitorcontract.FieldChainID:
		return m.AddedChainID()
	case monitorcontract.FieldStatus:
		return m.AddedStatus()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MonitorContractMutation) AddField(name string, value ent.Value) error {
	switch name {
	case monitorcontract.FieldChainID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddChainID(v)
		return nil
	case monitorcontract.FieldStatus:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStatus(v)
		return nil
	}
	return fmt.Errorf("unknown MonitorContract numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MonitorContractMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MonitorContractMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MonitorContractMutation) ClearField(name string) error {
	return fmt.Errorf("unknown MonitorContract nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MonitorContractMutation) ResetField(name string) error {
	switch name {
	case monitorcontract.FieldChainID:
		m.ResetChainID()
		return nil
	case monitorcontract.FieldAddress:
		m.ResetAddress()
		return nil
	case monitorcontract.FieldName:
		m.ResetName()
		return nil
	case monitorcontract.FieldAbi:
		m.ResetAbi()
		return nil
	case monitorcontract.FieldStatus:
		m.ResetStatus()
		return nil
	}
	return fmt.Errorf("unknown MonitorContract field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MonitorContractMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MonitorContractMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MonitorContractMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MonitorContractMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MonitorContractMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MonitorContractMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MonitorContractMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown MonitorContract unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MonitorContractMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown MonitorContract edge %s", name)
}

// MonitorEventMutation represents an operation that mutates the MonitorEvent nodes in the graph.
type MonitorEventMutation struct {
	config
	op             Op
	typ            string
	id             *uuid.UUID
	contract_id    *uuid.UUID
	event_name     *string
	mq_routing_key *string
	status         *int8
	addstatus      *int8
	last_block     *int64
	addlast_block  *int64
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*MonitorEvent, error)
	predicates     []predicate.MonitorEvent
}

var _ ent.Mutation = (*MonitorEventMutation)(nil)

// monitoreventOption allows management of the mutation configuration using functional options.
type monitoreventOption func(*MonitorEventMutation)

// newMonitorEventMutation creates new mutation for the MonitorEvent entity.
func newMonitorEventMutation(c config, op Op, opts ...monitoreventOption) *MonitorEventMutation {
	m := &MonitorEventMutation{
		config:        c,
		op:            op,
		typ:           TypeMonitorEvent,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMonitorEventID sets the ID field of the mutation.
func withMonitorEventID(id uuid.UUID) monitoreventOption {
	return func(m *MonitorEventMutation) {
		var (
			err   error
			once  sync.Once
			value *MonitorEvent
		)
		m.oldValue = func(ctx context.Context) (*MonitorEvent, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().MonitorEvent.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMonitorEvent sets the old MonitorEvent of the mutation.
func withMonitorEvent(node *MonitorEvent) monitoreventOption {
	return func(m *MonitorEventMutation) {
		m.oldValue = func(context.Context) (*MonitorEvent, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MonitorEventMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MonitorEventMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of MonitorEvent entities.
func (m *MonitorEventMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MonitorEventMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MonitorEventMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().MonitorEvent.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetContractID sets the "contract_id" field.
func (m *MonitorEventMutation) SetContractID(u uuid.UUID) {
	m.contract_id = &u
}

// ContractID returns the value of the "contract_id" field in the mutation.
func (m *MonitorEventMutation) ContractID() (r uuid.UUID, exists bool) {
	v := m.contract_id
	if v == nil {
		return
	}
	return *v, true
}

// OldContractID returns the old "contract_id" field's value of the MonitorEvent entity.
// If the MonitorEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MonitorEventMutation) OldContractID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContractID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContractID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContractID: %w", err)
	}
	return oldValue.ContractID, nil
}

// ResetContractID resets all changes to the "contract_id" field.
func (m *MonitorEventMutation) ResetContractID() {
	m.contract_id = nil
}

// SetEventName sets the "event_name" field.
func (m *MonitorEventMutation) SetEventName(s string) {
	m.event_name = &s
}

// EventName returns the value of the "event_name" field in the mutation.
func (m *MonitorEventMutation) EventName() (r string, exists bool) {
	v := m.event_name
	if v == nil {
		return
	}
	return *v, true
}

// OldEventName returns the old "event_name" field's value of the MonitorEvent entity.
// If the MonitorEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MonitorEventMutation) OldEventName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEventName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEventName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEventName: %w", err)
	}
	return oldValue.EventName, nil
}

// ResetEventName resets all changes to the "event_name" field.
func (m *MonitorEventMutation) ResetEventName() {
	m.event_name = nil
}

// SetMqRoutingKey sets the "mq_routing_key" field.
func (m *MonitorEventMutation) SetMqRoutingKey(s string) {
	m.mq_routing_key = &s
}

// MqRoutingKey returns the value of the "mq_routing_key" field in the mutation.
func (m *MonitorEventMutation) MqRoutingKey() (r string, exists bool) {
	v := m.mq_routing_key
	if v == nil {
		return
	}
	return *v, true
}

// OldMqRoutingKey returns the old "mq_routing_key" field's value of the MonitorEvent entity.
// If the MonitorEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MonitorEventMutation) OldMqRoutingKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMqRoutingKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMqRoutingKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMqRoutingKey: %w", err)
	}
	return oldValue.MqRoutingKey, nil
}

// ResetMqRoutingKey resets all changes to the "mq_routing_key" field.
func (m *MonitorEventMutation) ResetMqRoutingKey() {
	m.mq_routing_key = nil
}

// SetStatus sets the "status" field.
func (m *MonitorEventMutation) SetStatus(i int8) {
	m.status = &i
	m.addstatus = nil
}

// Status returns the value of the "status" field in the mutation.
func (m *MonitorEventMutation) Status() (r int8, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the MonitorEvent entity.
// If the MonitorEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MonitorEventMutation) OldStatus(ctx context.Context) (v int8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// AddStatus adds i to the "status" field.
func (m *MonitorEventMutation) AddStatus(i int8) {
	if m.addstatus != nil {
		*m.addstatus += i
	} else {
		m.addstatus = &i
	}
}

// AddedStatus returns the value that was added to the "status" field in this mutation.
func (m *MonitorEventMutation) AddedStatus() (r int8, exists bool) {
	v := m.addstatus
	if v == nil {
		return
	}
	return *v, true
}

// ResetStatus resets all changes to the "status" field.
func (m *MonitorEventMutation) ResetStatus() {
	m.status = nil
	m.addstatus = nil
}

// SetLastBlock sets the "last_block" field.
func (m *MonitorEventMutation) SetLastBlock(i int64) {
	m.last_block = &i
	m.addlast_block = nil
}

// LastBlock returns the value of the "last_block" field in the mutation.
func (m *MonitorEventMutation) LastBlock() (r int64, exists bool) {
	v := m.last_block
	if v == nil {
		return
	}
	return *v, true
}

// OldLastBlock returns the old "last_block" field's value of the MonitorEvent entity.
// If the MonitorEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MonitorEventMutation) OldLastBlock(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastBlock is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastBlock requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastBlock: %w", err)
	}
	return oldValue.LastBlock, nil
}

// AddLastBlock adds i to the "last_block" field.
func (m *MonitorEventMutation) AddLastBlock(i int64) {
	if m.addlast_block != nil {
		*m.addlast_block += i
	} else {
		m.addlast_block = &i
	}
}

// AddedLastBlock returns the value that was added to the "last_block" field in this mutation.
func (m *MonitorEventMutation) AddedLastBlock() (r int64, exists bool) {
	v := m.addlast_block
	if v == nil {
		return
	}
	return *v, true
}

// ResetLastBlock resets all changes to the "last_block" field.
func (m *MonitorEventMutation) ResetLastBlock() {
	m.last_block = nil
	m.addlast_block = nil
}

// Where appends a list predicates to the MonitorEventMutation builder.
func (m *MonitorEventMutation) Where(ps ...predicate.MonitorEvent) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MonitorEventMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MonitorEventMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.MonitorEvent, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MonitorEventMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MonitorEventMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (MonitorEvent).
func (m *MonitorEventMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MonitorEventMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.contract_id != nil {
		fields = append(fields, monitorevent.FieldContractID)
	}
	if m.event_name != nil {
		fields = append(fields, monitorevent.FieldEventName)
	}
	if m.mq_routing_key != nil {
		fields = append(fields, monitorevent.FieldMqRoutingKey)
	}
	if m.status != nil {
		fields = append(fields, monitorevent.FieldStatus)
	}
	if m.last_block != nil {
		fields = append(fields, monitorevent.FieldLastBlock)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MonitorEventMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case monitorevent.FieldContractID:
		return m.ContractID()
	case monitorevent.FieldEventName:
		return m.EventName()
	case monitorevent.FieldMqRoutingKey:
		return m.MqRoutingKey()
	case monitorevent.FieldStatus:
		return m.Status()
	case monitorevent.FieldLastBlock:
		return m.LastBlock()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MonitorEventMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case monitorevent.FieldContractID:
		return m.OldContractID(ctx)
	case monitorevent.FieldEventName:
		return m.OldEventName(ctx)
	case monitorevent.FieldMqRoutingKey:
		return m.OldMqRoutingKey(ctx)
	case monitorevent.FieldStatus:
		return m.OldStatus(ctx)
	case monitorevent.FieldLastBlock:
		return m.OldLastBlock(ctx)
	}
	return nil, fmt.Errorf("unknown MonitorEvent field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MonitorEventMutation) SetField(name string, value ent.Value) error {
	switch name {
	case monitorevent.FieldContractID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContractID(v)
		return nil
	case monitorevent.FieldEventName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEventName(v)
		return nil
	case monitorevent.FieldMqRoutingKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMqRoutingKey(v)
		return nil
	case monitorevent.FieldStatus:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case monitorevent.FieldLastBlock:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastBlock(v)
		return nil
	}
	return fmt.Errorf("unknown MonitorEvent field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MonitorEventMutation) AddedFields() []string {
	var fields []string
	if m.addstatus != nil {
		fields = append(fields, monitorevent.FieldStatus)
	}
	if m.addlast_block != nil {
		fields = append(fields, monitorevent.FieldLastBlock)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MonitorEventMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case monitorevent.FieldStatus:
		return m.AddedStatus()
	case monitorevent.FieldLastBlock:
		return m.AddedLastBlock()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MonitorEventMutation) AddField(name string, value ent.Value) error {
	switch name {
	case monitorevent.FieldStatus:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStatus(v)
		return nil
	case monitorevent.FieldLastBlock:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLastBlock(v)
		return nil
	}
	return fmt.Errorf("unknown MonitorEvent numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MonitorEventMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MonitorEventMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MonitorEventMutation) ClearField(name string) error {
	return fmt.Errorf("unknown MonitorEvent nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MonitorEventMutation) ResetField(name string) error {
	switch name {
	case monitorevent.FieldContractID:
		m.ResetContractID()
		return nil
	case monitorevent.FieldEventName:
		m.ResetEventName()
		return nil
	case monitorevent.FieldMqRoutingKey:
		m.ResetMqRoutingKey()
		return nil
	case monitorevent.FieldStatus:
		m.ResetStatus()
		return nil
	case monitorevent.FieldLastBlock:
		m.ResetLastBlock()
		return nil
	}
	return fmt.Errorf("unknown MonitorEvent field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MonitorEventMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MonitorEventMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MonitorEventMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MonitorEventMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MonitorEventMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MonitorEventMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MonitorEventMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown MonitorEvent unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MonitorEventMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown MonitorEvent edge %s", name)
}

// ParsedEventsLogMutation represents an operation that mutates the ParsedEventsLog nodes in the graph.
type ParsedEventsLogMutation struct {
	config
	op              Op
	typ             string
	id              *uuid.UUID
	uid             *string
	event_id        *uuid.UUID
	block_number    *int64
	addblock_number *int64
	tx_hash         *string
	log_index       *int64
	addlog_index    *int64
	parsed_data     *map[string]interface{}
	created_at      *time.Time
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*ParsedEventsLog, error)
	predicates      []predicate.ParsedEventsLog
}

var _ ent.Mutation = (*ParsedEventsLogMutation)(nil)

// parsedeventslogOption allows management of the mutation configuration using functional options.
type parsedeventslogOption func(*ParsedEventsLogMutation)

// newParsedEventsLogMutation creates new mutation for the ParsedEventsLog entity.
func newParsedEventsLogMutation(c config, op Op, opts ...parsedeventslogOption) *ParsedEventsLogMutation {
	m := &ParsedEventsLogMutation{
		config:        c,
		op:            op,
		typ:           TypeParsedEventsLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withParsedEventsLogID sets the ID field of the mutation.
func withParsedEventsLogID(id uuid.UUID) parsedeventslogOption {
	return func(m *ParsedEventsLogMutation) {
		var (
			err   error
			once  sync.Once
			value *ParsedEventsLog
		)
		m.oldValue = func(ctx context.Context) (*ParsedEventsLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ParsedEventsLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withParsedEventsLog sets the old ParsedEventsLog of the mutation.
func withParsedEventsLog(node *ParsedEventsLog) parsedeventslogOption {
	return func(m *ParsedEventsLogMutation) {
		m.oldValue = func(context.Context) (*ParsedEventsLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ParsedEventsLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ParsedEventsLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of ParsedEventsLog entities.
func (m *ParsedEventsLogMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ParsedEventsLogMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ParsedEventsLogMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ParsedEventsLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUID sets the "uid" field.
func (m *ParsedEventsLogMutation) SetUID(s string) {
	m.uid = &s
}

// UID returns the value of the "uid" field in the mutation.
func (m *ParsedEventsLogMutation) UID() (r string, exists bool) {
	v := m.uid
	if v == nil {
		return
	}
	return *v, true
}

// OldUID returns the old "uid" field's value of the ParsedEventsLog entity.
// If the ParsedEventsLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ParsedEventsLogMutation) OldUID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUID: %w", err)
	}
	return oldValue.UID, nil
}

// ResetUID resets all changes to the "uid" field.
func (m *ParsedEventsLogMutation) ResetUID() {
	m.uid = nil
}

// SetEventID sets the "event_id" field.
func (m *ParsedEventsLogMutation) SetEventID(u uuid.UUID) {
	m.event_id = &u
}

// EventID returns the value of the "event_id" field in the mutation.
func (m *ParsedEventsLogMutation) EventID() (r uuid.UUID, exists bool) {
	v := m.event_id
	if v == nil {
		return
	}
	return *v, true
}

// OldEventID returns the old "event_id" field's value of the ParsedEventsLog entity.
// If the ParsedEventsLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ParsedEventsLogMutation) OldEventID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEventID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEventID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEventID: %w", err)
	}
	return oldValue.EventID, nil
}

// ResetEventID resets all changes to the "event_id" field.
func (m *ParsedEventsLogMutation) ResetEventID() {
	m.event_id = nil
}

// SetBlockNumber sets the "block_number" field.
func (m *ParsedEventsLogMutation) SetBlockNumber(i int64) {
	m.block_number = &i
	m.addblock_number = nil
}

// BlockNumber returns the value of the "block_number" field in the mutation.
func (m *ParsedEventsLogMutation) BlockNumber() (r int64, exists bool) {
	v := m.block_number
	if v == nil {
		return
	}
	return *v, true
}

// OldBlockNumber returns the old "block_number" field's value of the ParsedEventsLog entity.
// If the ParsedEventsLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ParsedEventsLogMutation) OldBlockNumber(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBlockNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBlockNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBlockNumber: %w", err)
	}
	return oldValue.BlockNumber, nil
}

// AddBlockNumber adds i to the "block_number" field.
func (m *ParsedEventsLogMutation) AddBlockNumber(i int64) {
	if m.addblock_number != nil {
		*m.addblock_number += i
	} else {
		m.addblock_number = &i
	}
}

// AddedBlockNumber returns the value that was added to the "block_number" field in this mutation.
func (m *ParsedEventsLogMutation) AddedBlockNumber() (r int64, exists bool) {
	v := m.addblock_number
	if v == nil {
		return
	}
	return *v, true
}

// ResetBlockNumber resets all changes to the "block_number" field.
func (m *ParsedEventsLogMutation) ResetBlockNumber() {
	m.block_number = nil
	m.addblock_number = nil
}

// SetTxHash sets the "tx_hash" field.
func (m *ParsedEventsLogMutation) SetTxHash(s string) {
	m.tx_hash = &s
}

// TxHash returns the value of the "tx_hash" field in the mutation.
func (m *ParsedEventsLogMutation) TxHash() (r string, exists bool) {
	v := m.tx_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldTxHash returns the old "tx_hash" field's value of the ParsedEventsLog entity.
// If the ParsedEventsLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ParsedEventsLogMutation) OldTxHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTxHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTxHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTxHash: %w", err)
	}
	return oldValue.TxHash, nil
}

// ResetTxHash resets all changes to the "tx_hash" field.
func (m *ParsedEventsLogMutation) ResetTxHash() {
	m.tx_hash = nil
}

// SetLogIndex sets the "log_index" field.
func (m *ParsedEventsLogMutation) SetLogIndex(i int64) {
	m.log_index = &i
	m.addlog_index = nil
}

// LogIndex returns the value of the "log_index" field in the mutation.
func (m *ParsedEventsLogMutation) LogIndex() (r int64, exists bool) {
	v := m.log_index
	if v == nil {
		return
	}
	return *v, true
}

// OldLogIndex returns the old "log_index" field's value of the ParsedEventsLog entity.
// If the ParsedEventsLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ParsedEventsLogMutation) OldLogIndex(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLogIndex is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLogIndex requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLogIndex: %w", err)
	}
	return oldValue.LogIndex, nil
}

// AddLogIndex adds i to the "log_index" field.
func (m *ParsedEventsLogMutation) AddLogIndex(i int64) {
	if m.addlog_index != nil {
		*m.addlog_index += i
	} else {
		m.addlog_index = &i
	}
}

// AddedLogIndex returns the value that was added to the "log_index" field in this mutation.
func (m *ParsedEventsLogMutation) AddedLogIndex() (r int64, exists bool) {
	v := m.addlog_index
	if v == nil {
		return
	}
	return *v, true
}

// ResetLogIndex resets all changes to the "log_index" field.
func (m *ParsedEventsLogMutation) ResetLogIndex() {
	m.log_index = nil
	m.addlog_index = nil
}

// SetParsedData sets the "parsed_data" field.
func (m *ParsedEventsLogMutation) SetParsedData(value map[string]interface{}) {
	m.parsed_data = &value
}

// ParsedData returns the value of the "parsed_data" field in the mutation.
func (m *ParsedEventsLogMutation) ParsedData() (r map[string]interface{}, exists bool) {
	v := m.parsed_data
	if v == nil {
		return
	}
	return *v, true
}

// OldParsedData returns the old "parsed_data" field's value of the ParsedEventsLog entity.
// If the ParsedEventsLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ParsedEventsLogMutation) OldParsedData(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldParsedData is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldParsedData requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldParsedData: %w", err)
	}
	return oldValue.ParsedData, nil
}

// ResetParsedData resets all changes to the "parsed_data" field.
func (m *ParsedEventsLogMutation) ResetParsedData() {
	m.parsed_data = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *ParsedEventsLogMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ParsedEventsLogMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the ParsedEventsLog entity.
// If the ParsedEventsLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ParsedEventsLogMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ParsedEventsLogMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the ParsedEventsLogMutation builder.
func (m *ParsedEventsLogMutation) Where(ps ...predicate.ParsedEventsLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ParsedEventsLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ParsedEventsLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ParsedEventsLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ParsedEventsLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ParsedEventsLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ParsedEventsLog).
func (m *ParsedEventsLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ParsedEventsLogMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.uid != nil {
		fields = append(fields, parsedeventslog.FieldUID)
	}
	if m.event_id != nil {
		fields = append(fields, parsedeventslog.FieldEventID)
	}
	if m.block_number != nil {
		fields = append(fields, parsedeventslog.FieldBlockNumber)
	}
	if m.tx_hash != nil {
		fields = append(fields, parsedeventslog.FieldTxHash)
	}
	if m.log_index != nil {
		fields = append(fields, parsedeventslog.FieldLogIndex)
	}
	if m.parsed_data != nil {
		fields = append(fields, parsedeventslog.FieldParsedData)
	}
	if m.created_at != nil {
		fields = append(fields, parsedeventslog.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ParsedEventsLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case parsedeventslog.FieldUID:
		return m.UID()
	case parsedeventslog.FieldEventID:
		return m.EventID()
	case parsedeventslog.FieldBlockNumber:
		return m.BlockNumber()
	case parsedeventslog.FieldTxHash:
		return m.TxHash()
	case parsedeventslog.FieldLogIndex:
		return m.LogIndex()
	case parsedeventslog.FieldParsedData:
		return m.ParsedData()
	case parsedeventslog.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ParsedEventsLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case parsedeventslog.FieldUID:
		return m.OldUID(ctx)
	case parsedeventslog.FieldEventID:
		return m.OldEventID(ctx)
	case parsedeventslog.FieldBlockNumber:
		return m.OldBlockNumber(ctx)
	case parsedeventslog.FieldTxHash:
		return m.OldTxHash(ctx)
	case parsedeventslog.FieldLogIndex:
		return m.OldLogIndex(ctx)
	case parsedeventslog.FieldParsedData:
		return m.OldParsedData(ctx)
	case parsedeventslog.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown ParsedEventsLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ParsedEventsLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case parsedeventslog.FieldUID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUID(v)
		return nil
	case parsedeventslog.FieldEventID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEventID(v)
		return nil
	case parsedeventslog.FieldBlockNumber:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBlockNumber(v)
		return nil
	case parsedeventslog.FieldTxHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTxHash(v)
		return nil
	case parsedeventslog.FieldLogIndex:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLogIndex(v)
		return nil
	case parsedeventslog.FieldParsedData:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetParsedData(v)
		return nil
	case parsedeventslog.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown ParsedEventsLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ParsedEventsLogMutation) AddedFields() []string {
	var fields []string
	if m.addblock_number != nil {
		fields = append(fields, parsedeventslog.FieldBlockNumber)
	}
	if m.addlog_index != nil {
		fields = append(fields, parsedeventslog.FieldLogIndex)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ParsedEventsLogMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case parsedeventslog.FieldBlockNumber:
		return m.AddedBlockNumber()
	case parsedeventslog.FieldLogIndex:
		return m.AddedLogIndex()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ParsedEventsLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	case parsedeventslog.FieldBlockNumber:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddBlockNumber(v)
		return nil
	case parsedeventslog.FieldLogIndex:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLogIndex(v)
		return nil
	}
	return fmt.Errorf("unknown ParsedEventsLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ParsedEventsLogMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ParsedEventsLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ParsedEventsLogMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ParsedEventsLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ParsedEventsLogMutation) ResetField(name string) error {
	switch name {
	case parsedeventslog.FieldUID:
		m.ResetUID()
		return nil
	case parsedeventslog.FieldEventID:
		m.ResetEventID()
		return nil
	case parsedeventslog.FieldBlockNumber:
		m.ResetBlockNumber()
		return nil
	case parsedeventslog.FieldTxHash:
		m.ResetTxHash()
		return nil
	case parsedeventslog.FieldLogIndex:
		m.ResetLogIndex()
		return nil
	case parsedeventslog.FieldParsedData:
		m.ResetParsedData()
		return nil
	case parsedeventslog.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown ParsedEventsLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ParsedEventsLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ParsedEventsLogMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ParsedEventsLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ParsedEventsLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ParsedEventsLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ParsedEventsLogMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ParsedEventsLogMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ParsedEventsLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ParsedEventsLogMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ParsedEventsLog edge %s", name)
}
