// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nexus-chain/ent/parsedeventslog"
	"nexus-chain/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ParsedEventsLogUpdate is the builder for updating ParsedEventsLog entities.
type ParsedEventsLogUpdate struct {
	config
	hooks     []Hook
	mutation  *ParsedEventsLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ParsedEventsLogUpdate builder.
func (_u *ParsedEventsLogUpdate) Where(ps ...predicate.ParsedEventsLog) *ParsedEventsLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUID sets the "uid" field.
func (_u *ParsedEventsLogUpdate) SetUID(v string) *ParsedEventsLogUpdate {
	_u.mutation.SetUID(v)
	return _u
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (_u *ParsedEventsLogUpdate) SetNillableUID(v *string) *ParsedEventsLogUpdate {
	if v != nil {
		_u.SetUID(*v)
	}
	return _u
}

// SetChainID sets the "chain_id" field.
func (_u *ParsedEventsLogUpdate) SetChainID(v int) *ParsedEventsLogUpdate {
	_u.mutation.ResetChainID()
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *ParsedEventsLogUpdate) SetNillableChainID(v *int) *ParsedEventsLogUpdate {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// AddChainID adds value to the "chain_id" field.
func (_u *ParsedEventsLogUpdate) AddChainID(v int) *ParsedEventsLogUpdate {
	_u.mutation.AddChainID(v)
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *ParsedEventsLogUpdate) SetEventID(v uuid.UUID) *ParsedEventsLogUpdate {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *ParsedEventsLogUpdate) SetNillableEventID(v *uuid.UUID) *ParsedEventsLogUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetBlockNumber sets the "block_number" field.
func (_u *ParsedEventsLogUpdate) SetBlockNumber(v int64) *ParsedEventsLogUpdate {
	_u.mutation.ResetBlockNumber()
	_u.mutation.SetBlockNumber(v)
	return _u
}

// SetNillableBlockNumber sets the "block_number" field if the given value is not nil.
func (_u *ParsedEventsLogUpdate) SetNillableBlockNumber(v *int64) *ParsedEventsLogUpdate {
	if v != nil {
		_u.SetBlockNumber(*v)
	}
	return _u
}

// AddBlockNumber adds value to the "block_number" field.
func (_u *ParsedEventsLogUpdate) AddBlockNumber(v int64) *ParsedEventsLogUpdate {
	_u.mutation.AddBlockNumber(v)
	return _u
}

// SetTxHash sets the "tx_hash" field.
func (_u *ParsedEventsLogUpdate) SetTxHash(v string) *ParsedEventsLogUpdate {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *ParsedEventsLogUpdate) SetNillableTxHash(v *string) *ParsedEventsLogUpdate {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// SetLogIndex sets the "log_index" field.
func (_u *ParsedEventsLogUpdate) SetLogIndex(v int64) *ParsedEventsLogUpdate {
	_u.mutation.ResetLogIndex()
	_u.mutation.SetLogIndex(v)
	return _u
}

// SetNillableLogIndex sets the "log_index" field if the given value is not nil.
func (_u *ParsedEventsLogUpdate) SetNillableLogIndex(v *int64) *ParsedEventsLogUpdate {
	if v != nil {
		_u.SetLogIndex(*v)
	}
	return _u
}

// AddLogIndex adds value to the "log_index" field.
func (_u *ParsedEventsLogUpdate) AddLogIndex(v int64) *ParsedEventsLogUpdate {
	_u.mutation.AddLogIndex(v)
	return _u
}

// SetParsedData sets the "parsed_data" field.
func (_u *ParsedEventsLogUpdate) SetParsedData(v map[string]interface{}) *ParsedEventsLogUpdate {
	_u.mutation.SetParsedData(v)
	return _u
}

// Mutation returns the ParsedEventsLogMutation object of the builder.
func (_u *ParsedEventsLogUpdate) Mutation() *ParsedEventsLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ParsedEventsLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ParsedEventsLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ParsedEventsLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ParsedEventsLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ParsedEventsLogUpdate) check() error {
	if v, ok := _u.mutation.UID(); ok {
		if err := parsedeventslog.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "ParsedEventsLog.uid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TxHash(); ok {
		if err := parsedeventslog.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "ParsedEventsLog.tx_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LogIndex(); ok {
		if err := parsedeventslog.LogIndexValidator(v); err != nil {
			return &ValidationError{Name: "log_index", err: fmt.Errorf(`ent: validator failed for field "ParsedEventsLog.log_index": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ParsedEventsLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ParsedEventsLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ParsedEventsLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(parsedeventslog.Table, parsedeventslog.Columns, sqlgraph.NewFieldSpec(parsedeventslog.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UID(); ok {
		_spec.SetField(parsedeventslog.FieldUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChainID(); ok {
		_spec.SetField(parsedeventslog.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChainID(); ok {
		_spec.AddField(parsedeventslog.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(parsedeventslog.FieldEventID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.BlockNumber(); ok {
		_spec.SetField(parsedeventslog.FieldBlockNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBlockNumber(); ok {
		_spec.AddField(parsedeventslog.FieldBlockNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(parsedeventslog.FieldTxHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogIndex(); ok {
		_spec.SetField(parsedeventslog.FieldLogIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLogIndex(); ok {
		_spec.AddField(parsedeventslog.FieldLogIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ParsedData(); ok {
		_spec.SetField(parsedeventslog.FieldParsedData, field.TypeJSON, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{parsedeventslog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ParsedEventsLogUpdateOne is the builder for updating a single ParsedEventsLog entity.
type ParsedEventsLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ParsedEventsLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUID sets the "uid" field.
func (_u *ParsedEventsLogUpdateOne) SetUID(v string) *ParsedEventsLogUpdateOne {
	_u.mutation.SetUID(v)
	return _u
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (_u *ParsedEventsLogUpdateOne) SetNillableUID(v *string) *ParsedEventsLogUpdateOne {
	if v != nil {
		_u.SetUID(*v)
	}
	return _u
}

// SetChainID sets the "chain_id" field.
func (_u *ParsedEventsLogUpdateOne) SetChainID(v int) *ParsedEventsLogUpdateOne {
	_u.mutation.ResetChainID()
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *ParsedEventsLogUpdateOne) SetNillableChainID(v *int) *ParsedEventsLogUpdateOne {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// AddChainID adds value to the "chain_id" field.
func (_u *ParsedEventsLogUpdateOne) AddChainID(v int) *ParsedEventsLogUpdateOne {
	_u.mutation.AddChainID(v)
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *ParsedEventsLogUpdateOne) SetEventID(v uuid.UUID) *ParsedEventsLogUpdateOne {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *ParsedEventsLogUpdateOne) SetNillableEventID(v *uuid.UUID) *ParsedEventsLogUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetBlockNumber sets the "block_number" field.
func (_u *ParsedEventsLogUpdateOne) SetBlockNumber(v int64) *ParsedEventsLogUpdateOne {
	_u.mutation.ResetBlockNumber()
	_u.mutation.SetBlockNumber(v)
	return _u
}

// SetNillableBlockNumber sets the "block_number" field if the given value is not nil.
func (_u *ParsedEventsLogUpdateOne) SetNillableBlockNumber(v *int64) *ParsedEventsLogUpdateOne {
	if v != nil {
		_u.SetBlockNumber(*v)
	}
	return _u
}

// AddBlockNumber adds value to the "block_number" field.
func (_u *ParsedEventsLogUpdateOne) AddBlockNumber(v int64) *ParsedEventsLogUpdateOne {
	_u.mutation.AddBlockNumber(v)
	return _u
}

// SetTxHash sets the "tx_hash" field.
func (_u *ParsedEventsLogUpdateOne) SetTxHash(v string) *ParsedEventsLogUpdateOne {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *ParsedEventsLogUpdateOne) SetNillableTxHash(v *string) *ParsedEventsLogUpdateOne {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// SetLogIndex sets the "log_index" field.
func (_u *ParsedEventsLogUpdateOne) SetLogIndex(v int64) *ParsedEventsLogUpdateOne {
	_u.mutation.ResetLogIndex()
	_u.mutation.SetLogIndex(v)
	return _u
}

// SetNillableLogIndex sets the "log_index" field if the given value is not nil.
func (_u *ParsedEventsLogUpdateOne) SetNillableLogIndex(v *int64) *ParsedEventsLogUpdateOne {
	if v != nil {
		_u.SetLogIndex(*v)
	}
	return _u
}

// AddLogIndex adds value to the "log_index" field.
func (_u *ParsedEventsLogUpdateOne) AddLogIndex(v int64) *ParsedEventsLogUpdateOne {
	_u.mutation.AddLogIndex(v)
	return _u
}

// SetParsedData sets the "parsed_data" field.
func (_u *ParsedEventsLogUpdateOne) SetParsedData(v map[string]interface{}) *ParsedEventsLogUpdateOne {
	_u.mutation.SetParsedData(v)
	return _u
}

// Mutation returns the ParsedEventsLogMutation object of the builder.
func (_u *ParsedEventsLogUpdateOne) Mutation() *ParsedEventsLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the ParsedEventsLogUpdate builder.
func (_u *ParsedEventsLogUpdateOne) Where(ps ...predicate.ParsedEventsLog) *ParsedEventsLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ParsedEventsLogUpdateOne) Select(field string, fields ...string) *ParsedEventsLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ParsedEventsLog entity.
func (_u *ParsedEventsLogUpdateOne) Save(ctx context.Context) (*ParsedEventsLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ParsedEventsLogUpdateOne) SaveX(ctx context.Context) *ParsedEventsLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ParsedEventsLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ParsedEventsLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ParsedEventsLogUpdateOne) check() error {
	if v, ok := _u.mutation.UID(); ok {
		if err := parsedeventslog.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "ParsedEventsLog.uid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TxHash(); ok {
		if err := parsedeventslog.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "ParsedEventsLog.tx_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LogIndex(); ok {
		if err := parsedeventslog.LogIndexValidator(v); err != nil {
			return &ValidationError{Name: "log_index", err: fmt.Errorf(`ent: validator failed for field "ParsedEventsLog.log_index": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ParsedEventsLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ParsedEventsLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ParsedEventsLogUpdateOne) sqlSave(ctx context.Context) (_node *ParsedEventsLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(parsedeventslog.Table, parsedeventslog.Columns, sqlgraph.NewFieldSpec(parsedeventslog.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ParsedEventsLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, parsedeventslog.FieldID)
		for _, f := range fields {
			if !parsedeventslog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != parsedeventslog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UID(); ok {
		_spec.SetField(parsedeventslog.FieldUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChainID(); ok {
		_spec.SetField(parsedeventslog.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChainID(); ok {
		_spec.AddField(parsedeventslog.FieldChainID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(parsedeventslog.FieldEventID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.BlockNumber(); ok {
		_spec.SetField(parsedeventslog.FieldBlockNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBlockNumber(); ok {
		_spec.AddField(parsedeventslog.FieldBlockNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(parsedeventslog.FieldTxHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogIndex(); ok {
		_spec.SetField(parsedeventslog.FieldLogIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLogIndex(); ok {
		_spec.AddField(parsedeventslog.FieldLogIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ParsedData(); ok {
		_spec.SetField(parsedeventslog.FieldParsedData, field.TypeJSON, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ParsedEventsLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{parsedeventslog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
