// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"nexus-chain/ent/parsedeventslog"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ParsedEventsLog is the model entity for the ParsedEventsLog schema.
type ParsedEventsLog struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key ID
	ID uuid.UUID `json:"id,omitempty"`
	// Business UID
	UID string `json:"uid,omitempty"`
	// Chain ID
	ChainID int `json:"chain_id,omitempty"`
	// Foreign key to monitor_events.id
	EventID uuid.UUID `json:"event_id,omitempty"`
	// Block number
	BlockNumber int64 `json:"block_number,omitempty"`
	// Transaction hash
	TxHash string `json:"tx_hash,omitempty"`
	// Log index inside the transaction
	LogIndex int64 `json:"log_index,omitempty"`
	// Parsed business data
	ParsedData map[string]interface{} `json:"parsed_data,omitempty"`
	// Insert time
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ParsedEventsLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case parsedeventslog.FieldParsedData:
			values[i] = new([]byte)
		case parsedeventslog.FieldChainID, parsedeventslog.FieldBlockNumber, parsedeventslog.FieldLogIndex:
			values[i] = new(sql.NullInt64)
		case parsedeventslog.FieldUID, parsedeventslog.FieldTxHash:
			values[i] = new(sql.NullString)
		case parsedeventslog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case parsedeventslog.FieldID, parsedeventslog.FieldEventID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ParsedEventsLog fields.
func (_m *ParsedEventsLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case parsedeventslog.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case parsedeventslog.FieldUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				_m.UID = value.String
			}
		case parsedeventslog.FieldChainID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chain_id", values[i])
			} else if value.Valid {
				_m.ChainID = int(value.Int64)
			}
		case parsedeventslog.FieldEventID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value != nil {
				_m.EventID = *value
			}
		case parsedeventslog.FieldBlockNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field block_number", values[i])
			} else if value.Valid {
				_m.BlockNumber = value.Int64
			}
		case parsedeventslog.FieldTxHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tx_hash", values[i])
			} else if value.Valid {
				_m.TxHash = value.String
			}
		case parsedeventslog.FieldLogIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field log_index", values[i])
			} else if value.Valid {
				_m.LogIndex = value.Int64
			}
		case parsedeventslog.FieldParsedData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field parsed_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ParsedData); err != nil {
					return fmt.Errorf("unmarshal field parsed_data: %w", err)
				}
			}
		case parsedeventslog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ParsedEventsLog.
// This includes values selected through modifiers, order, etc.
func (_m *ParsedEventsLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ParsedEventsLog.
// Note that you need to call ParsedEventsLog.Unwrap() before calling this method if this ParsedEventsLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ParsedEventsLog) Update() *ParsedEventsLogUpdateOne {
	return NewParsedEventsLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ParsedEventsLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ParsedEventsLog) Unwrap() *ParsedEventsLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ParsedEventsLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ParsedEventsLog) String() string {
	var builder strings.Builder
	builder.WriteString("ParsedEventsLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("uid=")
	builder.WriteString(_m.UID)
	builder.WriteString(", ")
	builder.WriteString("chain_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChainID))
	builder.WriteString(", ")
	builder.WriteString("event_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventID))
	builder.WriteString(", ")
	builder.WriteString("block_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.BlockNumber))
	builder.WriteString(", ")
	builder.WriteString("tx_hash=")
	builder.WriteString(_m.TxHash)
	builder.WriteString(", ")
	builder.WriteString("log_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.LogIndex))
	builder.WriteString(", ")
	builder.WriteString("parsed_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParsedData))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ParsedEventsLogs is a parsable slice of ParsedEventsLog.
type ParsedEventsLogs []*ParsedEventsLog
