// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MonitorContract is the predicate function for monitorcontract builders.
type MonitorContract func(*sql.Selector)

// MonitorEvent is the predicate function for monitorevent builders.
type MonitorEvent func(*sql.Selector)

// ParsedEventsLog is the predicate function for parsedeventslog builders.
type ParsedEventsLog func(*sql.Selector)
